import { SideBarMenuItem } from "../types/menu"
import {
  Globe,
  DollarSign,
  Percent,
  CreditCard,
  List,
  FileText,
  Building,
  AppWindow,
  Settings,
  Lock,
  Users,
  User,
  UserCircle,
  Key,
  ArrowDownCircle,
  BarChart2,
  Activity,
  ArrowLeftRight,
  Shield,
  ShieldAlert,
  Phone,
  Blocks,
  CheckCircle,
  Zap,
} from "lucide-react"

export const adminMenus: SideBarMenuItem[] = [
  {
    label: "menu.administration",
    path: "/administration",
    icon: Settings,
    children: [
      {
        label: "menu.countries",
        path: "/administration/countries",
        icon: Globe,
        addPagePath: "/administration/countries/add",
        addButtonLabel: "menu.addCountry",
      },
      {
        label: "menu.currencies",
        path: "/administration/currencies",
        icon: DollarSign,
        addPagePath: "/administration/currencies/add",
        addButtonLabel: "menu.addCurrency",
      },
      {
        label: "menu.feeTypes",
        path: "/administration/fee-types",
        icon: Percent,
        addPagePath: "/administration/fee-types/add",
        addButtonLabel: "menu.addFeeType",
      },
      {
        label: "menu.paymentMethod",
        path: "/administration/payment-methods",
        icon: CreditCard,
        addPagePath: "/administration/payment-methods/add",
        addButtonLabel: "menu.addPaymentMethod",
      },
      {
        label: "menu.withdrawalMethod",
        path: "/administration/withdrawal-methods",
        icon: CreditCard,
        addPagePath: "/administration/withdrawal-methods/add",
        addButtonLabel: "menu.addWithdrawalMethod",
      },
      {
        label: "menu.feeConfigurations",
        path: "/administration/fee-configurations",
        icon: List,
        addPagePath: "/administration/fee-configurations/add",
        addButtonLabel: "menu.addFeeConfiguration",
      },
      {
        label: "menu.documentType",
        path: "/administration/document-types",
        icon: FileText,
        addPagePath: "/administration/document-types/add",
        addButtonLabel: "menu.addDocumentType",
      },
      {
        label: "menu.companyAppLimit",
        path: "/administration/company-app-limits",
        icon: Building,
        addPagePath: "/administration/company-app-limits/add",
        addButtonLabel: "menu.addCompanyAppLimit",
      },
      {
        label: "menu.settings",
        path: "/administration/settings",
        icon: Settings,
        addPagePath: "/administration/settings/add",
        addButtonLabel: "menu.addSetting",
      },
      {
        label: "menu.secureSettings",
        path: "/administration/secure-settings",
        icon: Lock,
        addPagePath: "/administration/secure-settings/add",
        addButtonLabel: "menu.addSecureSetting",
      },
    ],
  },
  {
    label: "menu.users",
    path: "/access-control/users",
    icon: Users,
    addPagePath: "users/add",
    addButtonLabel: "menu.addUser",
    children: [
      {
        label: "menu.users",
        path: "/access-control/users",
        icon: User,
        addPagePath: "/access-control/users/add",
        addButtonLabel: "menu.addUser",
      },
      {
        label: "menu.userProfiles",
        path: "/access-control/users/user-profiles",
        icon: UserCircle,
        addPagePath: "/access-control/users/user-profiles/add",
        addButtonLabel: "menu.addUserProfile",
      },
      {
        label: "menu.permissions",
        path: "/access-control/users/permissions",
        icon: Key,
      },
    ],
  },
  {
    label: "menu.companies",
    path: "/companies",
    icon: Building,
    addPagePath: "/companies/add",
    addButtonLabel: "menu.addCompany",
  },
  {
    label: "menu.applications",
    path: "/applications",
    icon: AppWindow,
    addPagePath: "/applications/add",
    addButtonLabel: "menu.addApplication",
  },
  {
    label: "menu.webhooks",
    path: "/webhooks",
    icon: Zap,
    addPagePath: "/webhooks/add",
    addButtonLabel: "menu.addWebhook",
  },
  {
    label: "menu.transactions",
    path: "/transactions",
    icon: ArrowLeftRight,
    children: [
      {
        label: "menu.all",
        path: "/transactions",
        icon: List,
      },
      {
        label: "menu.receipts",
        path: "/transactions/receipts",
        icon: DollarSign,
      },
      {
        label: "menu.withdrawals",
        path: "/transactions/withdrawals",
        icon: ArrowDownCircle,
      },
    ],
  },
  {
    label: "menu.auditSecurity",
    path: "/audit-security",
    icon: Shield,
    children: [
      {
        label: "menu.allowedIps",
        path: "/audit-security/allowed-ips",
        icon: CheckCircle,
      },
      {
        label: "menu.blockedIps",
        path: "/audit-security/blocked-ips",
        icon: Blocks,
      },
      {
        label: "menu.auditLogs",
        path: "/audit-security/audit-logs",
        icon: ShieldAlert,
      },
      {
        label: "menu.userDevices",
        path: "/audit-security/user-devices",
        icon: Phone,
      },
    ],
  },
  {
    label: "menu.monitoring",
    path: "/monitoring",
    icon: BarChart2,
    children: [
      {
        label: "menu.logs",
        path: "/monitoring/system-logs",
        icon: List,
      },
      {
        label: "menu.frontEvents",
        path: "/monitoring/front-events",
        icon: Activity,
      },
      {
        label: "menu.webHookLogs",
        path: "/monitoring/web-hook-logs",
        icon: ArrowDownCircle,
      },
    ],
  },
]
