import { BaseMenus } from "../types/menu"
import {
  Globe,
  DollarSign,
  Percent,
  CreditCard,
  List,
  FileText,
  Building,
  AppWindow,
  Settings,
  Lock,
  Users,
  User,
  UserCircle,
  Key,
  ArrowDownCircle,
  BarChart2,
  Activity,
  ArrowLeftRight,
  Shield,
  ShieldAlert,
  Phone,
  Blocks,
  CheckCircle,
  Zap,
  Gauge,
  ChartColumnIcon,
} from "lucide-react"

export const adminMenus: BaseMenus[] = [
  {
    groupTitle: "",
    elements: [
      {
        label: "menu.Dashboard",
        path: "/dashboard",
        icon: Gauge,
      },
      // {
      //   label: "menu.analytics",
      //   path: "/analytics",
      //   icon: ChartColumnIcon,
      // },
    ],
  },
  {
    groupTitle: "menu.system",
    elements: [
      {
        label: "menu.administration",
        path: "/administration",
        icon: Settings,
        children: [
          {
            label: "menu.countries",
            path: "/administration/countries",
            icon: Globe,
            addPagePath: "/administration/countries/add",
            addButtonLabel: "menu.addCountry",
            permission: "COUNTRY_VIEW",
          },
          {
            label: "menu.currencies",
            path: "/administration/currencies",
            icon: DollarSign,
            addPagePath: "/administration/currencies/add",
            addButtonLabel: "menu.addCurrency",
            permission: "CURRENCY_VIEW",
          },
          {
            label: "menu.feeTypes",
            path: "/administration/fee-types",
            icon: Percent,
            addPagePath: "/administration/fee-types/add",
            addButtonLabel: "menu.addFeeType",
            permission: "FEETYPE_VIEW",
          },
          {
            label: "menu.paymentMethod",
            path: "/administration/payment-methods",
            icon: CreditCard,
            addPagePath: "/administration/payment-methods/add",
            addButtonLabel: "menu.addPaymentMethod",
            permission: "PAYMENTMETHOD_VIEW",
          },
          {
            label: "menu.withdrawalMethod",
            path: "/administration/withdrawal-methods",
            icon: CreditCard,
            addPagePath: "/administration/withdrawal-methods/add",
            addButtonLabel: "menu.addWithdrawalMethod",
            permission: "WITHDRAWALMETHOD_VIEW",
          },
          {
            label: "menu.feeConfigurations",
            path: "/administration/fee-configurations",
            icon: List,
            addPagePath: "/administration/fee-configurations/add",
            addButtonLabel: "menu.addFeeConfiguration",
            permission: "FEECONFIGURATION_VIEW",
          },
          {
            label: "menu.documentType",
            path: "/administration/document-types",
            icon: FileText,
            addPagePath: "/administration/document-types/add",
            addButtonLabel: "menu.addDocumentType",
            permission: "DOCUMENTSTYPE_VIEW",
          },
          {
            label: "menu.companyAppLimit",
            path: "/administration/company-app-limits",
            icon: Building,
            addPagePath: "/administration/company-app-limits/add",
            addButtonLabel: "menu.addCompanyAppLimit",
            permission: "COMPANYAPPLIMIT_VIEW",
          },
          {
            label: "menu.settings",
            path: "/administration/settings",
            icon: Settings,
            addPagePath: "/administration/settings/add",
            addButtonLabel: "menu.addSetting",
            permission: "SETTING_VIEW",
          },
          {
            label: "menu.secureSettings",
            path: "/administration/secure-settings",
            icon: Lock,
            addPagePath: "/administration/secure-settings/add",
            addButtonLabel: "menu.addSecureSetting",
            permission: "SECURESETTING_VIEW",
          },
        ],
      },
      {
        label: "menu.access-control",
        path: "/access-control/users",
        icon: Users,
        addPagePath: "users/add",
        addButtonLabel: "menu.addUser",
        children: [
          {
            label: "menu.users",
            path: "/access-control/users",
            icon: User,
            addPagePath: "/access-control/users/add",
            addButtonLabel: "menu.addUser",
            permission: "USER_VIEW",
          },
          {
            label: "menu.userProfiles",
            path: "/access-control/user-profiles",
            icon: UserCircle,
            addPagePath: "/access-control/user-profiles/add",
            addButtonLabel: "menu.addUserProfile",
            permission: "USERPROFILE_VIEW",
          },
        ],
      },
    ],
  },
  {
    groupTitle: "menu.general",
    elements: [
      {
        label: "menu.companies",
        path: "/companies",
        icon: Building,
        addPagePath: "/companies/add",
        addButtonLabel: "menu.addCompany",
        permission: "COMPANY_VIEW",
      },
      {
        label: "menu.applications",
        path: "/applications",
        icon: AppWindow,
        addPagePath: "/applications/add",
        addButtonLabel: "menu.addApplication",
        permission: "APPLICATION_VIEW",
      },
      {
        label: "menu.transactions",
        path: "/transactions",
        icon: ArrowLeftRight,
        children: [
          // {
          //   label: "menu.all",
          //   path: "/transactions",
          //   icon: List,
          //   permission: "TRANSACTION_VIEW",
          // },
          {
            label: "menu.receipts",
            path: "/transactions/receipts",
            icon: DollarSign,
            permission: "RECEIPTSREADMODEL_VIEW",
          },
          {
            label: "menu.withdrawals",
            path: "/transactions/withdrawals",
            icon: ArrowDownCircle,
            permission: "WITHDRAWALSREADMODEL_VIEW",
          },
        ],
      },
    ],
  },
  {
    groupTitle: "menu.it",
    elements: [
      {
        label: "menu.webhooks",
        path: "/webhooks",
        icon: Zap,
        addPagePath: "/webhooks/add",
        addButtonLabel: "menu.addWebhook",
        permission: "WEBHOOK_VIEW",
      },
      {
        label: "menu.auditSecurity",
        path: "/audit-security",
        icon: Shield,
        children: [
          {
            label: "menu.allowedIps",
            path: "/audit-security/allowed-ips",
            icon: CheckCircle,
            permission: "ALLOWEDIP_VIEW",
          },
          {
            label: "menu.blockedIps",
            path: "/audit-security/blocked-ips",
            icon: Blocks,
            permission: "BLOCKEDIP_VIEW",
          },
          {
            label: "menu.auditLogs",
            path: "/audit-security/audit-logs",
            icon: ShieldAlert,
            permission: "AUDITLOG_VIEW",
          },
          {
            label: "menu.userDevices",
            path: "/audit-security/user-devices",
            icon: Phone,
            permission: "USERDEVICE_VIEW",
          },
        ],
      },
      {
        label: "menu.monitoring",
        path: "/monitoring",
        icon: BarChart2,
        children: [
          {
            label: "menu.logs",
            path: "/monitoring/system-logs",
            icon: List,
            permission: "LOG_VIEW",
          },
          {
            label: "menu.frontEvents",
            path: "/monitoring/front-events",
            icon: Activity,
            permission: "FRONTEVENTLOG_VIEW",
          },
          {
            label: "menu.webHookLogs",
            path: "/monitoring/web-hook-logs",
            icon: ArrowDownCircle,
            permission: "WEBHOOKLOG_VIEW",
          },
        ],
      },
    ],
  },
]
