import { BaseMenus } from "../types/menu"
import {
  Gauge,
  Megaphone,
  Users,
  MessageSquare,
  Building,
  CreditCard,
  Settings,
  FileText,
  Activity,
  Lock,
  Globe,
  Plug,
  Tag,
  Wallet,
  Bell,
  Box,
  Link,
  Briefcase,
  UserCheck,
  Layers,
  BarChart,
  FileCode,
  Zap,
  RefreshCw,
  Shield,
  Key,
  Database,
  File,
  Cpu,
  Radio,
  DollarSign,
  Euro,
  List,
} from "lucide-react"

export const adminMenus: BaseMenus[] = [
  {
    groupTitle: "",
    elements: [
      {
        label: "menu.Dashboard",
        path: "/dashboard",
        icon: Gauge,
      },
    ],
  },
  {
    groupTitle: "menu.campaignManagement",
    elements: [
      {
        label: "menu.Campaign",
        path: "/campaigns",
        icon: Megaphone,
        permission: "CAMPAIGN_VIEW",
      },
      {
        label: "menu.CampaignChannel",
        path: "/campaign-channels",
        icon: Radio,
        permission: "CAMPAIGNCHANNEL_VIEW",
      },
      {
        label: "menu.CampaignSegment",
        path: "/campaign-segments",
        icon: Users,
        permission: "CAMPAIGNSEGMENT_VIEW",
      },
      {
        label: "menu.CampaignStatistic",
        path: "/campaign-statistics",
        icon: BarChart,
        permission: "CAMPAIGNSTATISTIC_VIEW",
      },
      {
        label: "menu.CampaignStep",
        path: "/campaign-steps",
        icon: Layers,
        permission: "CAMPAIGNSTEP_VIEW",
      },
      {
        label: "menu.Template",
        path: "/templates",
        icon: FileCode,
        permission: "TEMPLATE_VIEW",
      },
      {
        label: "menu.TemplateChannel",
        path: "/template-channels",
        icon: FileCode,
        permission: "TEMPLATECHANNEL_VIEW",
      },
    ],
  },
  {
    groupTitle: "menu.clientManagement",
    elements: [
      {
        label: "menu.Client",
        path: "/clients",
        icon: Users,
        permission: "CLIENT_VIEW",
      },
      {
        label: "menu.ClientChannelPreference",
        path: "/client-channel-preferences",
        icon: Settings,
        permission: "CLIENTCHANNELPREFERENCE_VIEW",
      },
      {
        label: "menu.ClientImport",
        path: "/client-imports",
        icon: Database,
        permission: "CLIENTIMPORT_VIEW",
      },
      {
        label: "menu.ClientSegment",
        path: "/client-segments",
        icon: Users,
        permission: "CLIENTSEGMENT_VIEW",
      },
      {
        label: "menu.ClientSegmentMember",
        path: "/client-segment-members",
        icon: UserCheck,
        permission: "CLIENTSEGMENTMEMBER_VIEW",
      },
      {
        label: "menu.User",
        path: "/users",
        icon: Users,
        permission: "USER_VIEW",
      },
      {
        label: "menu.UserProfile",
        path: "/user-profiles",
        icon: UserCheck,
        permission: "USERPROFILE_VIEW",
      },
    ],
  },
  {
    groupTitle: "menu.communications",
    elements: [
      {
        label: "menu.Channel",
        path: "/channels",
        icon: MessageSquare,
        permission: "CHANNEL_VIEW",
      },
      {
        label: "menu.Message",
        path: "/messages",
        icon: MessageSquare,
        permission: "MESSAGE_VIEW",
      },
      {
        label: "menu.MessageEvent",
        path: "/message-events",
        icon: Activity,
        permission: "MESSAGEEVENT_VIEW",
      },
      {
        label: "menu.Notification",
        path: "/notifications",
        icon: Bell,
        permission: "NOTIFICATION_VIEW",
      },
      {
        label: "menu.WebhookDelivery",
        path: "/webhook-deliveries",
        icon: Link,
        permission: "WEBHOOKDELIVERY_VIEW",
      },
      {
        label: "menu.WebhookEndpoint",
        path: "/webhook-endpoints",
        icon: Link,
        permission: "WEBHOOKENDPOINT_VIEW",
      },
    ],
  },
  {
    groupTitle: "menu.companiesAndProducts",
    elements: [
      {
        label: "menu.Company",
        path: "/companies",
        icon: Building,
        permission: "COMPANY_VIEW",
      },
      {
        label: "menu.CompanyApiKey",
        path: "/company-api-keys",
        icon: Key,
        permission: "COMPANYAPIKEY_VIEW",
      },
      {
        label: "menu.CompanyChannel",
        path: "/company-channels",
        icon: Radio,
        permission: "COMPANYCHANNEL_VIEW",
      },
      {
        label: "menu.CompanySetting",
        path: "/company-settings",
        icon: Settings,
        permission: "COMPANYSETTING_VIEW",
      },
      {
        label: "menu.CompanyVerification",
        path: "/company-verifications",
        icon: Shield,
        permission: "COMPANYVERIFICATION_VIEW",
      },
      {
        label: "menu.Product",
        path: "/products",
        icon: Box,
        permission: "PRODUCT_VIEW",
      },
      {
        label: "menu.ProductChannel",
        path: "/product-channels",
        icon: Radio,
        permission: "PRODUCTCHANNEL_VIEW",
      },
      {
        label: "menu.ProductChannelStatistic",
        path: "/product-channel-statistics",
        icon: BarChart,
        permission: "PRODUCTCHANNELSTATISTIC_VIEW",
      },
    ],
  },
  {
    groupTitle: "menu.billingAndFinance",
    elements: [
      {
        label: "menu.Invoice",
        path: "/invoices",
        icon: FileText,
        permission: "INVOICE_VIEW",
      },
      {
        label: "menu.Payment",
        path: "/payments",
        icon: DollarSign,
        permission: "PAYMENT_VIEW",
      },
      {
        label: "menu.PaymentMethod",
        path: "/payment-methods",
        icon: CreditCard,
        permission: "PAYMENTMETHOD_VIEW",
      },
      {
        label: "menu.Pricing",
        path: "/pricing",
        icon: Tag,
        permission: "PRICING_VIEW",
      },
      {
        label: "menu.Subscription",
        path: "/subscriptions",
        icon: RefreshCw,
        permission: "SUBSCRIPTION_VIEW",
      },
      {
        label: "menu.SubscriptionPlan",
        path: "/subscription-plans",
        icon: List,
        permission: "SUBSCRIPTIONPLAN_VIEW",
      },
      {
        label: "menu.Wallet",
        path: "/wallets",
        icon: Wallet,
        permission: "WALLET_VIEW",
      },
      {
        label: "menu.WalletTransaction",
        path: "/wallet-transactions",
        icon: Activity,
        permission: "WALLETTRANSACTION_VIEW",
      },
      {
        label: "menu.Currency",
        path: "/currencies",
        icon: Euro,
        permission: "CURRENCY_VIEW",
      },
    ],
  },
  {
    groupTitle: "menu.systemAndSettings",
    elements: [
      {
        label: "menu.AuditLog",
        path: "/audit-logs",
        icon: FileText,
        permission: "AUDITLOG_VIEW",
      },
      {
        label: "menu.Blocklist",
        path: "/blocklists",
        icon: Shield,
        permission: "BLOCKLIST_VIEW",
      },
      {
        label: "menu.Connector",
        path: "/connectors",
        icon: Plug,
        permission: "CONNECTOR_VIEW",
      },
      {
        label: "menu.Country",
        path: "/countries",
        icon: Globe,
        permission: "COUNTRY_VIEW",
      },
      {
        label: "menu.EntityTag",
        path: "/entity-tags",
        icon: Tag,
        permission: "ENTITYTAG_VIEW",
      },
      {
        label: "menu.File",
        path: "/files",
        icon: File,
        permission: "FILE_VIEW",
      },
      {
        label: "menu.Integration",
        path: "/integrations",
        icon: Plug,
        permission: "INTEGRATION_VIEW",
      },
      {
        label: "menu.IntegrationSyncLog",
        path: "/integration-sync-logs",
        icon: Activity,
        permission: "INTEGRATIONSYNCLOG_VIEW",
      },
      {
        label: "menu.Job",
        path: "/jobs",
        icon: Briefcase,
        permission: "JOB_VIEW",
      },
      {
        label: "menu.Provider",
        path: "/providers",
        icon: Zap,
        permission: "PROVIDER_VIEW",
      },
      {
        label: "menu.ProviderCallback",
        path: "/provider-callbacks",
        icon: Activity,
        permission: "PROVIDERCALLBACK_VIEW",
      },
      {
        label: "menu.SecureSetting",
        path: "/secure-settings",
        icon: Lock,
        permission: "SECURESETTING_VIEW",
      },
      {
        label: "menu.Setting",
        path: "/settings",
        icon: Settings,
        permission: "SETTING_VIEW",
      },
      {
        label: "menu.SysLog",
        path: "/sys-logs",
        icon: Cpu,
        permission: "SYSLOG_VIEW",
      },
      {
        label: "menu.Tag",
        path: "/tags",
        icon: Tag,
        permission: "TAG_VIEW",
      },
    ],
  },
]
