export enum ACTION {
  /** #REGION START AUDITLOG ACTIONS*/
  AUDITLOG_READ = "AUDITLOG_READ",
  /** #REGION END */

  /** #REGION START BLOCKLIST ACTIONS*/
  BLOCKLIST_READ = "BLOCKLIST_READ",
  BLOCKLIST_WRITE = "BLOCKLIST_WRITE",
  BLOCKLIST_EDIT = "BLOCKLIST_EDIT",
  BLOCKLIST_DELETE = "BLOCKLIST_DELETE",
  /** #REGION END */

  /** #REGION START CAMPAIGN ACTIONS*/
  CAMPAIGN_READ = "CAMPAIGN_READ",
  CAMPAIGN_WRITE = "CAMPAIGN_WRITE",
  CAMPAIGN_EDIT = "CAMPAIGN_EDIT",
  CAMPAIGN_DELETE = "CAMPAIGN_DELETE",
  CAMPAIGN_ACTIVATE = "CAMPAIGN_ACTIVATE",
  CAMPAIGN_DEACTIVATE = "CAMPAIGN_DEACTIVATE",
  /** #REGION END */

  /** #REGION START CAMPAIGNCHANNEL ACTIONS*/
  CAMPAIGNCHANNEL_READ = "CAMPAIGNCHANNEL_READ",
  CAMPAIGNCHANNEL_WRITE = "CAMPAIGNCHANNEL_WRITE",
  CAMPAIGNCHANNEL_EDIT = "CAMPAIGNCHANNEL_EDIT",
  CAMPAIGNCHANNEL_DELETE = "CAMPAIGNCHANNEL_DELETE",
  /** #REGION END */

  /** #REGION START CAMPAIGNSEGMENT ACTIONS*/
  CAMPAIGNSEGMENT_READ = "CAMPAIGNSEGMENT_READ",
  CAMPAIGNSEGMENT_WRITE = "CAMPAIGNSEGMENT_WRITE",
  CAMPAIGNSEGMENT_EDIT = "CAMPAIGNSEGMENT_EDIT",
  CAMPAIGNSEGMENT_DELETE = "CAMPAIGNSEGMENT_DELETE",
  /** #REGION END */

  /** #REGION START CAMPAIGNSTATISTIC ACTIONS*/
  CAMPAIGNSTATISTIC_READ = "CAMPAIGNSTATISTIC_READ",
  /** #REGION END */

  /** #REGION START CAMPAIGNSTEP ACTIONS*/
  CAMPAIGNSTEP_READ = "CAMPAIGNSTEP_READ",
  CAMPAIGNSTEP_WRITE = "CAMPAIGNSTEP_WRITE",
  CAMPAIGNSTEP_EDIT = "CAMPAIGNSTEP_EDIT",
  CAMPAIGNSTEP_DELETE = "CAMPAIGNSTEP_DELETE",
  /** #REGION END */

  /** #REGION START CHANNEL ACTIONS*/
  CHANNEL_READ = "CHANNEL_READ",
  CHANNEL_WRITE = "CHANNEL_WRITE",
  CHANNEL_EDIT = "CHANNEL_EDIT",
  CHANNEL_DELETE = "CHANNEL_DELETE",
  CHANNEL_CONFIG = "CHANNEL_CONFIG",
  /** #REGION END */

  /** #REGION START CLIENT ACTIONS*/
  CLIENT_READ = "CLIENT_READ",
  CLIENT_WRITE = "CLIENT_WRITE",
  CLIENT_EDIT = "CLIENT_EDIT",
  CLIENT_DELETE = "CLIENT_DELETE",
  /** #REGION END */

  /** #REGION START CLIENTCHANNELPREFERENCE ACTIONS*/
  CLIENTCHANNELPREFERENCE_READ = "CLIENTCHANNELPREFERENCE_READ",
  CLIENTCHANNELPREFERENCE_WRITE = "CLIENTCHANNELPREFERENCE_WRITE",
  CLIENTCHANNELPREFERENCE_EDIT = "CLIENTCHANNELPREFERENCE_EDIT",
  /** #REGION END */

  /** #REGION START CLIENTIMPORT ACTIONS*/
  CLIENTIMPORT_READ = "CLIENTIMPORT_READ",
  CLIENTIMPORT_WRITE = "CLIENTIMPORT_WRITE",
  CLIENTIMPORT_DELETE = "CLIENTIMPORT_DELETE",
  /** #REGION END */

  /** #REGION START CLIENTSEGMENT ACTIONS*/
  CLIENTSEGMENT_READ = "CLIENTSEGMENT_READ",
  CLIENTSEGMENT_WRITE = "CLIENTSEGMENT_WRITE",
  CLIENTSEGMENT_EDIT = "CLIENTSEGMENT_EDIT",
  CLIENTSEGMENT_DELETE = "CLIENTSEGMENT_DELETE",
  /** #REGION END */

  /** #REGION START CLIENTSEGMENTMEMBER ACTIONS*/
  CLIENTSEGMENTMEMBER_READ = "CLIENTSEGMENTMEMBER_READ",
  CLIENTSEGMENTMEMBER_WRITE = "CLIENTSEGMENTMEMBER_WRITE",
  CLIENTSEGMENTMEMBER_DELETE = "CLIENTSEGMENTMEMBER_DELETE",
  /** #REGION END */

  /** #REGION START COMPANY ACTIONS*/
  COMPANY_READ = "COMPANY_READ",
  COMPANY_WRITE = "COMPANY_WRITE",
  COMPANY_EDIT = "COMPANY_EDIT",
  COMPANY_CONFIG = "COMPANY_CONFIG",
  /** #REGION END */

  /** #REGION START COMPANYAPIKEY ACTIONS*/
  COMPANYAPIKEY_READ = "COMPANYAPIKEY_READ",
  COMPANYAPIKEY_WRITE = "COMPANYAPIKEY_WRITE",
  COMPANYAPIKEY_EDIT = "COMPANYAPIKEY_EDIT",
  COMPANYAPIKEY_DELETE = "COMPANYAPIKEY_DELETE",
  /** #REGION END */

  /** #REGION START COMPANYCHANNEL ACTIONS*/
  COMPANYCHANNEL_READ = "COMPANYCHANNEL_READ",
  COMPANYCHANNEL_WRITE = "COMPANYCHANNEL_WRITE",
  COMPANYCHANNEL_EDIT = "COMPANYCHANNEL_EDIT",
  COMPANYCHANNEL_DELETE = "COMPANYCHANNEL_DELETE",
  /** #REGION END */

  /** #REGION START COMPANYSETTING ACTIONS*/
  COMPANYSETTING_READ = "COMPANYSETTING_READ",
  COMPANYSETTING_WRITE = "COMPANYSETTING_WRITE",
  COMPANYSETTING_EDIT = "COMPANYSETTING_EDIT",
  /** #REGION END */

  /** #REGION START COMPANYVERIFICATION ACTIONS*/
  COMPANYVERIFICATION_READ = "COMPANYVERIFICATION_READ",
  COMPANYVERIFICATION_WRITE = "COMPANYVERIFICATION_WRITE",
  /** #REGION END */

  /** #REGION START CONNECTOR ACTIONS*/
  CONNECTOR_READ = "CONNECTOR_READ",
  CONNECTOR_WRITE = "CONNECTOR_WRITE",
  CONNECTOR_EDIT = "CONNECTOR_EDIT",
  CONNECTOR_DELETE = "CONNECTOR_DELETE",
  /** #REGION END */

  /** #REGION START COUNTRY ACTIONS*/
  COUNTRY_READ = "COUNTRY_READ",
  /** #REGION END */

  /** #REGION START CURRENCY ACTIONS*/
  CURRENCY_READ = "CURRENCY_READ",
  /** #REGION END */

  /** #REGION START ENTITYTAG ACTIONS*/
  ENTITYTAG_READ = "ENTITYTAG_READ",
  ENTITYTAG_WRITE = "ENTITYTAG_WRITE",
  ENTITYTAG_EDIT = "ENTITYTAG_EDIT",
  ENTITYTAG_DELETE = "ENTITYTAG_DELETE",
  /** #REGION END */

  /** #REGION START FILE ACTIONS*/
  FILE_READ = "FILE_READ",
  FILE_WRITE = "FILE_WRITE",
  FILE_DELETE = "FILE_DELETE",
  /** #REGION END */

  /** #REGION START INTEGRATION ACTIONS*/
  INTEGRATION_READ = "INTEGRATION_READ",
  INTEGRATION_WRITE = "INTEGRATION_WRITE",
  INTEGRATION_EDIT = "INTEGRATION_EDIT",
  INTEGRATION_DELETE = "INTEGRATION_DELETE",
  INTEGRATION_CONFIG = "INTEGRATION_CONFIG",
  /** #REGION END */

  /** #REGION START INTEGRATIONSYNCLOG ACTIONS*/
  INTEGRATIONSYNCLOG_READ = "INTEGRATIONSYNCLOG_READ",
  /** #REGION END */

  /** #REGION START INVOICE ACTIONS*/
  INVOICE_READ = "INVOICE_READ",
  INVOICE_WRITE = "INVOICE_WRITE",
  INVOICE_DELETE = "INVOICE_DELETE",
  /** #REGION END */

  /** #REGION START JOB ACTIONS*/
  JOB_READ = "JOB_READ",
  /** #REGION END */

  /** #REGION START MESSAGE ACTIONS*/
  MESSAGE_READ = "MESSAGE_READ",
  MESSAGE_DELETE = "MESSAGE_DELETE",
  /** #REGION END */

  /** #REGION START MESSAGEEVENT ACTIONS*/
  MESSAGEEVENT_READ = "MESSAGEEVENT_READ",
  /** #REGION END */

  /** #REGION START NOTIFICATION ACTIONS*/
  NOTIFICATION_READ = "NOTIFICATION_READ",
  NOTIFICATION_WRITE = "NOTIFICATION_WRITE",
  /** #REGION END */

  /** #REGION START PAYMENT ACTIONS*/
  PAYMENT_READ = "PAYMENT_READ",
  PAYMENT_WRITE = "PAYMENT_WRITE",
  PAYMENT_DELETE = "PAYMENT_DELETE",
  /** #REGION END */

  /** #REGION START PAYMENTMETHOD ACTIONS*/
  PAYMENTMETHOD_READ = "PAYMENTMETHOD_READ",
  PAYMENTMETHOD_WRITE = "PAYMENTMETHOD_WRITE",
  PAYMENTMETHOD_EDIT = "PAYMENTMETHOD_EDIT",
  PAYMENTMETHOD_DELETE = "PAYMENTMETHOD_DELETE",
  PAYMENTMETHOD_CONFIG = "PAYMENTMETHOD_CONFIG",
  /** #REGION END */

  /** #REGION START PRICING ACTIONS*/
  PRICING_READ = "PRICING_READ",
  PRICING_WRITE = "PRICING_WRITE",
  PRICING_EDIT = "PRICING_EDIT",
  PRICING_DELETE = "PRICING_DELETE",
  PRICING_CONFIG = "PRICING_CONFIG",
  /** #REGION END */

  /** #REGION START PRODUCT ACTIONS*/
  PRODUCT_READ = "PRODUCT_READ",
  PRODUCT_WRITE = "PRODUCT_WRITE",
  PRODUCT_EDIT = "PRODUCT_EDIT",
  PRODUCT_DELETE = "PRODUCT_DELETE",
  PRODUCT_ACTIVATE = "PRODUCT_ACTIVATE",
  PRODUCT_DEACTIVATE = "PRODUCT_DEACTIVATE",
  /** #REGION END */

  /** #REGION START PRODUCTCHANNEL ACTIONS*/
  PRODUCTCHANNEL_READ = "PRODUCTCHANNEL_READ",
  PRODUCTCHANNEL_WRITE = "PRODUCTCHANNEL_WRITE",
  PRODUCTCHANNEL_EDIT = "PRODUCTCHANNEL_EDIT",
  PRODUCTCHANNEL_DELETE = "PRODUCTCHANNEL_DELETE",
  /** #REGION END */

  /** #REGION START PRODUCTCHANNELSTATISTIC ACTIONS*/
  PRODUCTCHANNELSTATISTIC_READ = "PRODUCTCHANNELSTATISTIC_READ",
  /** #REGION END */

  /** #REGION START PROVIDER ACTIONS*/
  PROVIDER_READ = "PROVIDER_READ",
  PROVIDER_WRITE = "PROVIDER_WRITE",
  PROVIDER_EDIT = "PROVIDER_EDIT",
  PROVIDER_DELETE = "PROVIDER_DELETE",
  PROVIDER_CONFIG = "PROVIDER_CONFIG",
  /** #REGION END */

  /** #REGION START PROVIDERCALLBACK ACTIONS*/
  PROVIDERCALLBACK_READ = "PROVIDERCALLBACK_READ",
  /** #REGION END */

  /** #REGION START SECURESETTING ACTIONS*/
  SECURESETTING_READ = "SECURESETTING_READ",
  SECURESETTING_WRITE = "SECURESETTING_WRITE",
  SECURESETTING_CONFIG = "SECURESETTING_CONFIG",
  /** #REGION END */

  /** #REGION START SETTING ACTIONS*/
  SETTING_READ = "SETTING_READ",
  SETTING_WRITE = "SETTING_WRITE",
  SETTING_CONFIG = "SETTING_CONFIG",
  /** #REGION END */

  /** #REGION START SUBSCRIPTION ACTIONS*/
  SUBSCRIPTION_READ = "SUBSCRIPTION_READ",
  SUBSCRIPTION_WRITE = "SUBSCRIPTION_WRITE",
  SUBSCRIPTION_EDIT = "SUBSCRIPTION_EDIT",
  SUBSCRIPTION_DELETE = "SUBSCRIPTION_DELETE",
  /** #REGION END */

  /** #REGION START SUBSCRIPTIONPLAN ACTIONS*/
  SUBSCRIPTIONPLAN_READ = "SUBSCRIPTIONPLAN_READ",
  SUBSCRIPTIONPLAN_WRITE = "SUBSCRIPTIONPLAN_WRITE",
  SUBSCRIPTIONPLAN_EDIT = "SUBSCRIPTIONPLAN_EDIT",
  SUBSCRIPTIONPLAN_DELETE = "SUBSCRIPTIONPLAN_DELETE",
  SUBSCRIPTIONPLAN_CONFIG = "SUBSCRIPTIONPLAN_CONFIG",
  /** #REGION END */

  /** #REGION START SYSLOG ACTIONS*/
  SYSLOG_READ = "SYSLOG_READ",
  /** #REGION END */

  /** #REGION START TAG ACTIONS*/
  TAG_READ = "TAG_READ",
  TAG_WRITE = "TAG_WRITE",
  TAG_EDIT = "TAG_EDIT",
  TAG_DELETE = "TAG_DELETE",
  /** #REGION END */

  /** #REGION START TEMPLATE ACTIONS*/
  TEMPLATE_READ = "TEMPLATE_READ",
  TEMPLATE_WRITE = "TEMPLATE_WRITE",
  TEMPLATE_EDIT = "TEMPLATE_EDIT",
  TEMPLATE_DELETE = "TEMPLATE_DELETE",
  TEMPLATE_ACTIVATE = "TEMPLATE_ACTIVATE",
  TEMPLATE_DEACTIVATE = "TEMPLATE_DEACTIVATE",
  /** #REGION END */

  /** #REGION START TEMPLATECHANNEL ACTIONS*/
  TEMPLATECHANNEL_READ = "TEMPLATECHANNEL_READ",
  TEMPLATECHANNEL_WRITE = "TEMPLATECHANNEL_WRITE",
  TEMPLATECHANNEL_EDIT = "TEMPLATECHANNEL_EDIT",
  TEMPLATECHANNEL_DELETE = "TEMPLATECHANNEL_DELETE",
  /** #REGION END */

  /** #REGION START USER ACTIONS*/
  USER_READ = "USER_READ",
  USER_WRITE = "USER_WRITE",
  USER_EDIT = "USER_EDIT",
  USER_DELETE = "USER_DELETE",
  USER_UNLOCK = "USER_UNLOCK",
  USER_LOCK = "USER_LOCK",
  USER_ACTIVATE = "USER_ACTIVATE",
  USER_DEACTIVATE = "USER_DEACTIVATE",
  /** #REGION END */

  /** #REGION START USERPROFILE ACTIONS*/
  USERPROFILE_READ = "USERPROFILE_READ",
  USERPROFILE_WRITE = "USERPROFILE_WRITE",
  USERPROFILE_EDIT = "USERPROFILE_EDIT",
  USERPROFILE_DELETE = "USERPROFILE_DELETE",
  USERPROFILE_CONFIG = "USERPROFILE_CONFIG",
  /** #REGION END */

  /** #REGION START WALLET ACTIONS*/
  WALLET_READ = "WALLET_READ",
  WALLET_WRITE = "WALLET_WRITE",
  WALLET_CONFIG = "WALLET_CONFIG",
  /** #REGION END */

  /** #REGION START WALLETTRANSACTION ACTIONS*/
  WALLETTRANSACTION_READ = "WALLETTRANSACTION_READ",
  /** #REGION END */

  /** #REGION START WEBHOOKDELIVERY ACTIONS*/
  WEBHOOKDELIVERY_READ = "WEBHOOKDELIVERY_READ",
  /** #REGION END */

  /** #REGION START WEBHOOKENDPOINT ACTIONS*/
  WEBHOOKENDPOINT_READ = "WEBHOOKENDPOINT_READ",
  WEBHOOKENDPOINT_WRITE = "WEBHOOKENDPOINT_WRITE",
  WEBHOOKENDPOINT_EDIT = "WEBHOOKENDPOINT_EDIT",
  WEBHOOKENDPOINT_DELETE = "WEBHOOKENDPOINT_DELETE",
  /** #REGION END */

  /** #REGION START DASHBOARD ACTIONS*/
  DASHBOARD_READ = "DASHBOARD_READ",
  /** #REGION END */

  /** #REGION START WHATSAPP ACTIONS*/
  WHATSAPP_READ = "WHATSAPP_READ",
  /** #REGION END */

}

export enum PERMISSION {}
