/**
 * Jeu d'émojis du sélecteur — extrait de `emoji-picker-react` (jeu `fr`), la
 * bibliothèque utilisée par le composeur du web, pour que les deux clients
 * proposent les mêmes émojis dans le même ordre.
 *
 * Régénéré depuis `node_modules/emoji-picker-react/dist/data/emojis-fr.json`.
 * Les glyphes apparus après Unicode 13 sont écartés : beaucoup d'Android ne les
 * ont pas et les afficheraient en tofu.
 */

export interface EmojiGroup {
  id: string;
  label: string;
  /** Émoji représentant le groupe dans la barre d'onglets. */
  icon: string;
  /** `[glyphe, mots-clés]` — les mots-clés alimentent la recherche. */
  emojis: [string, string][];
}

/**
 * Retire les accents pour la recherche : les mots-clés du jeu sont accentués
 * (« gâteau »), or personne ne tape les accents dans un champ de recherche.
 *
 * Table explicite plutôt que `normalize("NFD")` : la normalisation Unicode
 * dépend de l'ICU embarqué par Hermes, et le vocabulaire ici est français.
 */
const ACCENTS: Record<string, string> = {
  à: "a", â: "a", ä: "a", á: "a", ã: "a",
  ç: "c",
  é: "e", è: "e", ê: "e", ë: "e",
  î: "i", ï: "i", í: "i",
  ô: "o", ö: "o", ó: "o", õ: "o",
  ù: "u", û: "u", ü: "u", ú: "u",
  ÿ: "y", ñ: "n", œ: "oe", æ: "ae",
  // Lettres romanisées présentes dans quelques mots-clés (mahjong, yin/yang…).
  ā: "a", ī: "i", ō: "o", ū: "u", ǐ: "i",
  // Ponctuation typographique : personne ne la tape au clavier.
  "’": "'", "\u202f": " ",
};

export function deburr(text: string): string {
  return text.toLowerCase().replace(/[^\x00-\x7f]/g, (c) => ACCENTS[c] ?? c);
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: "smileys_people",
    label: "Frimousses et personnes",
    icon: "😀",
    emojis: [
      ["😀", "sourire visage rieur"],
      ["😃", "sourire visage souriant avec de grands yeux"],
      ["😄", "sourire visage très souriant aux yeux rieurs"],
      ["😁", "dents sourire"],
      ["😆", "rire bouche"],
      ["😅", "sourire visage souriant avec une goutte de sueur"],
      ["🤣", "rire visage"],
      ["😂", "larmes sourire"],
      ["🙂", "sourire visage avec un léger sourire"],
      ["🙃", "tête renversée"],
      ["😉", "visage clin d’œil"],
      ["😊", "œil rougir"],
      ["😇", "ange visage souriant avec auréole"],
      ["🥰", "aimer amour"],
      ["😍", "œil cœur"],
      ["🤩", "yeux visage"],
      ["😘", "cœur bisou"],
      ["😗", "bisou visage faisant un bisou"],
      ["☺️", "sourire visage souriant"],
      ["😚", "bisou visage faisant un bisou avec les yeux fermés"],
      ["😙", "bisou visage aux yeux rieurs faisant un bisou"],
      ["🥲", "ému fier"],
      ["😋", "miam langue"],
      ["😛", "langue visage"],
      ["😜", "œil langue"],
      ["🤪", "œil grand"],
      ["😝", "œil goût"],
      ["🤑", "yeux argent"],
      ["🤗", "câlin gentil"],
      ["🤭", "oups visage avec une main sur la bouche"],
      ["🤫", "chut silence"],
      ["🤔", "visage réflexion"],
      ["🤐", "bouche visage"],
      ["🤨", "méfiant sceptique"],
      ["😐", "neutre visage neutre"],
      ["😑", "neutre visage"],
      ["😶", "muet visage sans bouche"],
      ["😏", "malin sourire"],
      ["😒", "blasé visage"],
      ["🙄", "yeux roulement"],
      ["😬", "visage grimace"],
      ["🤥", "visage menteur"],
      ["😌", "visage soulagement"],
      ["😔", "déçu pensif"],
      ["😪", "visage sommeil"],
      ["🤤", "baver visage"],
      ["😴", "zzz visage"],
      ["😷", "masque visage avec masque"],
      ["🤒", "malade visage"],
      ["🤕", "tête bandage"],
      ["🤢", "nausée visage"],
      ["🤮", "vomi malade"],
      ["🤧", "rhume visage"],
      ["🥵", "chaud fièvre"],
      ["🥶", "froid gelure"],
      ["🥴", "rond hébété"],
      ["😵", "visage tournis"],
      ["🤯", "choqué tête qui explose"],
      ["🤠", "cowboy visage"],
      ["🥳", "fête chapeau"],
      ["🥸", "faux nez lunettes"],
      ["😎", "lunettes de soleil visage avec lunettes de soleil"],
      ["🤓", "geek visage"],
      ["🧐", "vieux jeu collet monté"],
      ["😕", "confus visage"],
      ["😟", "visage inquiet"],
      ["🙁", "visage mécontent"],
      ["☹️", "visage mécontent"],
      ["😮", "surpris visage avec bouche ouverte"],
      ["😯", "visage surpris"],
      ["😲", "choc visage"],
      ["😳", "rouge visage"],
      ["🥺", "pitié supplication"],
      ["😦", "déçu bouche"],
      ["😧", "visage angoisse"],
      ["😨", "peur apeuré"],
      ["😰", "froid sueur"],
      ["😥", "pfiou visage triste mais soulagé"],
      ["😢", "larmes visage qui pleure"],
      ["😭", "larme pleurs"],
      ["😱", "cri peur"],
      ["😖", "visage déconcerté"],
      ["😣", "visage persévérant"],
      ["😞", "déçu visage"],
      ["😓", "sueur froide"],
      ["😩", "visage épuisé"],
      ["😫", "visage fatigue"],
      ["🥱", "ennui bâiller"],
      ["😤", "visage triomphe"],
      ["😡", "colère visage"],
      ["😠", "colère visage en colère"],
      ["🤬", "juron visage avec des symboles dans la bouche"],
      ["😈", "cornes visage"],
      ["👿", "mauvais diablotin"],
      ["💀", "mort crâne"],
      ["☠️", "os mort"],
      ["💩", "caca crotte"],
      ["🤡", "clown visage"],
      ["👹", "ogre japonais"],
      ["👺", "monstre japonais"],
      ["👻", "visage fantôme"],
      ["👽", "ovni alien"],
      ["👾", "espace monstre"],
      ["🤖", "robot visage"],
      ["😺", "visage sourire"],
      ["😸", "visage sourire"],
      ["😹", "joie visage"],
      ["😻", "cœur yeux"],
      ["😼", "visage ironique"],
      ["😽", "bisou visage"],
      ["🙀", "oh visage"],
      ["😿", "larme triste"],
      ["😾", "ennui bouder"],
      ["🙈", "singe aveugle"],
      ["🙉", "singe sourd"],
      ["🙊", "muet singe"],
      ["💌", "amour lettre"],
      ["💘", "cœur flèche"],
      ["💝", "cœur ruban"],
      ["💖", "cœur cœur étincelant"],
      ["💗", "cœur cœur grandissant"],
      ["💓", "cœur cœur battant"],
      ["💞", "cœurs cœurs qui tournent"],
      ["💕", "amour cœurs"],
      ["💟", "cœur décoration avec cœur"],
      ["❣️", "cœur exclamation"],
      ["💔", "cœur cœur brisé"],
      ["❤️", "cœur cœur rouge"],
      ["🧡", "orange cœur orange"],
      ["💛", "cœur cœur jaune"],
      ["💚", "cœur cœur vert"],
      ["💙", "cœur cœur bleu"],
      ["💜", "cœur cœur violet"],
      ["🤎", "brun marron"],
      ["🖤", "noir cœur noir"],
      ["🤍", "blanc cœur blanc"],
      ["💋", "rouge baiser"],
      ["💯", "cent cent points"],
      ["💢", "colère dessin"],
      ["💥", "explosion collision"],
      ["💫", "tournis étourdissement"],
      ["💦", "sueur éclaboussures"],
      ["💨", "filer décamper"],
      ["🕳️", "trou"],
      ["💬", "bulle dialogue"],
      ["👁️‍🗨️", "œil témoin"],
      ["🗨️", "bulle dialogue"],
      ["🗯️", "bulle colère"],
      ["💭", "bulle pensée"],
      ["💤", "dormir endormi"],
      ["👋", "main coucou"],
      ["🤚", "main levée"],
      ["🖐️", "main main levée doigts écartés"],
      ["✋", "main feuille"],
      ["🖖", "main vulcain"],
      ["👌", "ok main"],
      ["🤌", "main geste"],
      ["🤏", "peu un peu"],
      ["✌️", "main ciseaux"],
      ["🤞", "main doigts"],
      ["🤟", "main amour"],
      ["🤘", "main cornes"],
      ["🤙", "main appel"],
      ["👈", "main doigt"],
      ["👉", "main doigt"],
      ["👆", "main doigt"],
      ["🖕", "main doigt"],
      ["👇", "bas main"],
      ["☝️", "main doigt"],
      ["👍", "main super"],
      ["👎", "nul main"],
      ["✊", "main poing"],
      ["👊", "main poing"],
      ["🤛", "main poing"],
      ["🤜", "main poing"],
      ["👏", "bravo mains"],
      ["🙌", "air mains"],
      ["👐", "main ouvert"],
      ["🤲", "mains prière"],
      ["🤝", "mains poignée"],
      ["🙏", "mains prière"],
      ["✍️", "main écrire"],
      ["💅", "maquillage vernis à ongles"],
      ["🤳", "selfie téléphone"],
      ["💪", "corps biceps"],
      ["🦾", "prothèse bras robot"],
      ["🦿", "prothèse jambe robot"],
      ["🦵", "jambe membre"],
      ["🦶", "pied pas lourd"],
      ["👂", "corps oreille"],
      ["🦻", "malentendant accessibilité"],
      ["👃", "nez corps"],
      ["🧠", "cerveau intelligent"],
      ["🫀", "cœur pouls"],
      ["🫁", "organe poumons"],
      ["🦷", "dent dentiste"],
      ["🦴", "os squelette"],
      ["👀", "œil yeux"],
      ["👁️", "œil corps"],
      ["👅", "corps langue"],
      ["👄", "corps bouche"],
      ["👶", "bébé"],
      ["🧒", "jeune enfant"],
      ["👦", "jeune garçon"],
      ["👧", "fille jeune"],
      ["🧑", "adulte genre neutre"],
      ["👱", "blond cheveux"],
      ["👨", "homme"],
      ["🧔", "barbe personne barbue"],
      ["👨‍🦰", "homme cheveux roux"],
      ["👨‍🦱", "homme cheveux bouclés"],
      ["👨‍🦳", "homme cheveux blancs"],
      ["👨‍🦲", "homme chauve"],
      ["👩", "femme"],
      ["👩‍🦰", "femme cheveux roux"],
      ["🧑‍🦰", "adulte cheveux roux"],
      ["👩‍🦱", "femme cheveux bouclés"],
      ["🧑‍🦱", "adulte genre neutre"],
      ["👩‍🦳", "femme cheveux blancs"],
      ["🧑‍🦳", "adulte genre neutre"],
      ["👩‍🦲", "femme chauve"],
      ["🧑‍🦲", "adulte chauve"],
      ["👱‍♀️", "blonde cheveux"],
      ["👱‍♂️", "blond cheveux"],
      ["🧓", "âgé adulte"],
      ["👴", "âgé homme"],
      ["👵", "âgée femme"],
      ["🙍", "froncer sourcils"],
      ["🙍‍♂️", "geste homme"],
      ["🙍‍♀️", "femme geste"],
      ["🙎", "moue geste"],
      ["🙎‍♂️", "boude geste"],
      ["🙎‍♀️", "boude femme"],
      ["🙅", "main geste"],
      ["🙅‍♂️", "main geste"],
      ["🙅‍♀️", "main femme"],
      ["🙆", "ok main"],
      ["🙆‍♂️", "ok main"],
      ["🙆‍♀️", "ok main"],
      ["💁", "aide main"],
      ["💁‍♂️", "homme paume vers le haut"],
      ["💁‍♀️", "femme paume vers le haut"],
      ["🙋", "main geste"],
      ["🙋‍♂️", "geste homme"],
      ["🙋‍♀️", "femme geste"],
      ["🧏", "sourd oreille"],
      ["🧏‍♂️", "sourd oreille"],
      ["🧏‍♀️", "sourd oreille"],
      ["🙇", "geste désolé"],
      ["🙇‍♂️", "geste homme"],
      ["🙇‍♀️", "femme geste"],
      ["🤦", "visage incrédulité"],
      ["🤦‍♂️", "homme paume"],
      ["🤦‍♀️", "femme paume"],
      ["🤷", "doute ignorance"],
      ["🤷‍♂️", "homme ignorance"],
      ["🤷‍♀️", "femme ignorance"],
      ["🧑‍⚕️", "santé docteur"],
      ["👨‍⚕️", "homme santé"],
      ["👩‍⚕️", "femme santé"],
      ["🧑‍🎓", "diplôme étudiant"],
      ["👨‍🎓", "homme diplômé"],
      ["👩‍🎓", "femme diplômée"],
      ["🧑‍🏫", "formateur enseignant"],
      ["👨‍🏫", "homme enseignant"],
      ["👩‍🏫", "femme enseignante"],
      ["🧑‍⚖️", "juge balance"],
      ["👨‍⚖️", "homme balance"],
      ["👩‍⚖️", "juge femme"],
      ["🧑‍🌾", "fermier fermière"],
      ["👨‍🌾", "homme fermier"],
      ["👩‍🌾", "femme fermière"],
      ["🧑‍🍳", "chef cuisinier"],
      ["👨‍🍳", "chef homme"],
      ["👩‍🍳", "chef femme"],
      ["🧑‍🔧", "artisan plombier"],
      ["👨‍🔧", "homme plombier"],
      ["👩‍🔧", "femme plombier"],
      ["🧑‍🏭", "usine ouvrier"],
      ["👨‍🏭", "usine ouvrier"],
      ["👩‍🏭", "usine ouvrière"],
      ["🧑‍💼", "bureau affaires"],
      ["👨‍💼", "homme bureau"],
      ["👩‍💼", "femme bureau"],
      ["🧑‍🔬", "chimiste scientifique"],
      ["👨‍🔬", "homme chimiste"],
      ["👩‍🔬", "femme chimiste"],
      ["🧑‍💻", "logiciels développeur"],
      ["👨‍💻", "homme logiciels"],
      ["👩‍💻", "femme logiciels"],
      ["🧑‍🎤", "rock star"],
      ["👨‍🎤", "rock star"],
      ["👩‍🎤", "rock star"],
      ["🧑‍🎨", "artiste palette"],
      ["👨‍🎨", "homme artiste"],
      ["👩‍🎨", "femme artiste"],
      ["🧑‍✈️", "avion pilote"],
      ["👨‍✈️", "avion homme"],
      ["👩‍✈️", "avion femme"],
      ["🧑‍🚀", "fusée astronaute"],
      ["👨‍🚀", "fusée homme"],
      ["👩‍🚀", "femme fusée"],
      ["🧑‍🚒", "pompier camion de pompiers"],
      ["👨‍🚒", "homme pompier"],
      ["👩‍🚒", "femme pompier"],
      ["👮", "flic police"],
      ["👮‍♂️", "flic homme"],
      ["👮‍♀️", "flic femme"],
      ["🕵️", "espion détective"],
      ["🕵️‍♂️", "homme espion"],
      ["🕵️‍♀️", "femme espionne"],
      ["💂", "garde"],
      ["💂‍♂️", "garde homme"],
      ["💂‍♀️", "femme garde"],
      ["🥷", "ninja furtif"],
      ["👷", "casque ouvrier"],
      ["👷‍♂️", "homme ouvrier"],
      ["👷‍♀️", "femme bâtiment"],
      ["🤴", "prince"],
      ["👸", "princesse fantastique"],
      ["👳", "turban personne en turban"],
      ["👳‍♂️", "homme turban"],
      ["👳‍♀️", "femme turban"],
      ["👲", "homme chapeau"],
      ["🧕", "hijab tichel"],
      ["🤵", "marié smoking"],
      ["🤵‍♂️", "homme smoking"],
      ["🤵‍♀️", "femme smoking"],
      ["👰", "voile mariée"],
      ["👰‍♂️", "homme voile"],
      ["👰‍♀️", "femme voile"],
      ["🤰", "femme enceinte"],
      ["🤱", "bébé sein"],
      ["👩‍🍼", "bébé femme"],
      ["👨‍🍼", "bébé homme"],
      ["🧑‍🍼", "bébé biberon"],
      ["👼", "ange bébé"],
      ["🎅", "noël père"],
      ["🤶", "mère noël"],
      ["🧑‍🎄", "noël santa"],
      ["🦸", "bien héros"],
      ["🦸‍♂️", "bien homme"],
      ["🦸‍♀️", "bien femme"],
      ["🦹", "mal méchant"],
      ["🦹‍♂️", "mal homme"],
      ["🦹‍♀️", "mal femme"],
      ["🧙", "mage sorcier"],
      ["🧙‍♂️", "sorcier magicien"],
      ["🧙‍♀️", "sorcière mage femme"],
      ["🧚", "puck obéron"],
      ["🧚‍♂️", "puck obéron"],
      ["🧚‍♀️", "fée titania"],
      ["🧛", "vampire dracula"],
      ["🧛‍♂️", "dracula mort vivant"],
      ["🧛‍♀️", "vampire femme morte vivante"],
      ["🧜", "sirène triton"],
      ["🧜‍♂️", "triton"],
      ["🧜‍♀️", "sirène"],
      ["🧝", "elfe magique"],
      ["🧝‍♂️", "magique elfe homme"],
      ["🧝‍♀️", "magique elfe femme"],
      ["🧞", "génie djinn"],
      ["🧞‍♂️", "djinn génie homme"],
      ["🧞‍♀️", "djinn génie femme"],
      ["🧟", "zombie mort vivant"],
      ["🧟‍♂️", "mort vivant zombie homme"],
      ["🧟‍♀️", "zombie femme morte vivante"],
      ["💆", "salon visage"],
      ["💆‍♂️", "homme visage"],
      ["💆‍♀️", "femme visage"],
      ["💇", "salon beauté"],
      ["💇‍♂️", "homme coiffure"],
      ["💇‍♀️", "femme coiffure"],
      ["🚶", "marche piéton"],
      ["🚶‍♂️", "homme marche"],
      ["🚶‍♀️", "femme marche"],
      ["🧍", "debout personne debout"],
      ["🧍‍♂️", "homme debout"],
      ["🧍‍♀️", "femme debout"],
      ["🧎", "à genoux personne à genoux"],
      ["🧎‍♂️", "homme à genoux"],
      ["🧎‍♀️", "femme à genoux"],
      ["🧑‍🦯", "aveugle accessibilité"],
      ["👨‍🦯", "homme aveugle"],
      ["👩‍🦯", "femme aveugle"],
      ["🧑‍🦼", "accessibilité fauteuil roulant"],
      ["👨‍🦼", "homme accessibilité"],
      ["👩‍🦼", "femme accessibilité"],
      ["🧑‍🦽", "accessibilité fauteuil roulant"],
      ["👨‍🦽", "homme accessibilité"],
      ["👩‍🦽", "femme accessibilité"],
      ["🏃", "coureur jogging"],
      ["🏃‍♂️", "homme jogging"],
      ["🏃‍♀️", "femme jogging"],
      ["💃", "danse femme"],
      ["🕺", "danse homme"],
      ["🕴️", "homme affaires"],
      ["👯", "femme fille"],
      ["👯‍♂️", "fête homme"],
      ["👯‍♀️", "fête femme"],
      ["🧖", "sauna hammam"],
      ["🧖‍♂️", "sauna hammam"],
      ["🧖‍♀️", "sauna hammam"],
      ["🧗", "grimpeur alpiniste"],
      ["🧗‍♂️", "grimpeur alpiniste"],
      ["🧗‍♀️", "alpiniste grimpeuse"],
      ["🤺", "épée sport"],
      ["🏇", "sport cheval"],
      ["⛷️", "neige sport"],
      ["🏂", "neige sport"],
      ["🏌️", "golf balle"],
      ["🏌️‍♂️", "golf homme"],
      ["🏌️‍♀️", "golf femme"],
      ["🏄", "sport personne faisant du surf"],
      ["🏄‍♂️", "surf homme"],
      ["🏄‍♀️", "surf femme"],
      ["🚣", "barque bateau"],
      ["🚣‍♂️", "homme barque"],
      ["🚣‍♀️", "femme barque"],
      ["🏊", "sport personne nageant"],
      ["🏊‍♂️", "nage homme"],
      ["🏊‍♀️", "nage femme"],
      ["⛹️", "sport personne avec ballon"],
      ["⛹️‍♂️", "homme ballon"],
      ["⛹️‍♀️", "femme ballon"],
      ["🏋️", "sport haltérophile"],
      ["🏋️‍♂️", "homme haltérophile"],
      ["🏋️‍♀️", "femme haltérophile"],
      ["🚴", "vélo cycliste"],
      ["🚴‍♂️", "vélo homme"],
      ["🚴‍♀️", "vélo femme"],
      ["🚵", "vélo montagne"],
      ["🚵‍♂️", "vtt vélo"],
      ["🚵‍♀️", "vtt vélo"],
      ["🤸", "roue sport"],
      ["🤸‍♂️", "roue homme"],
      ["🤸‍♀️", "roue femme"],
      ["🤼", "lutte sport"],
      ["🤼‍♂️", "lutte sport"],
      ["🤼‍♀️", "lutte sport"],
      ["🤽", "sport water polo"],
      ["🤽‍♂️", "homme sport"],
      ["🤽‍♀️", "femme sport"],
      ["🤾", "sport handball"],
      ["🤾‍♂️", "homme sport"],
      ["🤾‍♀️", "femme sport"],
      ["🤹", "jongler jongleur"],
      ["🤹‍♂️", "homme jongleur"],
      ["🤹‍♀️", "femme jonglage"],
      ["🧘", "yoga méditation"],
      ["🧘‍♂️", "yoga méditation"],
      ["🧘‍♀️", "yoga méditation"],
      ["🛀", "bain baignoire"],
      ["🛌", "lit personne au lit"],
      ["🧑‍🤝‍🧑", "main couple"],
      ["👭", "couple femmes"],
      ["👫", "femme homme"],
      ["👬", "couple hommes"],
      ["💏", "bisou baiser"],
      ["👩‍❤️‍💋‍👨", "bisou femme"],
      ["👨‍❤️‍💋‍👨", "bisou homme"],
      ["👩‍❤️‍💋‍👩", "bisou femme"],
      ["💑", "cœur amour"],
      ["👩‍❤️‍👨", "cœur amour"],
      ["👨‍❤️‍👨", "cœur amour"],
      ["👩‍❤️‍👩", "cœur amour"],
      ["👨‍👩‍👦", "mère père"],
      ["👨‍👩‍👧", "mère père"],
      ["👨‍👩‍👧‍👦", "mère père"],
      ["👨‍👩‍👦‍👦", "mère père"],
      ["👨‍👩‍👧‍👧", "mère père"],
      ["👨‍👨‍👦", "mère père"],
      ["👨‍👨‍👧", "mère père"],
      ["👨‍👨‍👧‍👦", "mère père"],
      ["👨‍👨‍👦‍👦", "mère père"],
      ["👨‍👨‍👧‍👧", "mère père"],
      ["👩‍👩‍👦", "mère père"],
      ["👩‍👩‍👧", "mère père"],
      ["👩‍👩‍👧‍👦", "mère père"],
      ["👩‍👩‍👦‍👦", "mère père"],
      ["👩‍👩‍👧‍👧", "mère père"],
      ["👨‍👦", "mère père"],
      ["👨‍👦‍👦", "mère père"],
      ["👨‍👧", "mère père"],
      ["👨‍👧‍👦", "mère père"],
      ["👨‍👧‍👧", "mère père"],
      ["👩‍👦", "mère père"],
      ["👩‍👦‍👦", "mère père"],
      ["👩‍👧", "mère père"],
      ["👩‍👧‍👦", "mère père"],
      ["👩‍👧‍👧", "mère père"],
      ["🗣️", "parler silhouette"],
      ["👤", "buste silhouette de buste"],
      ["👥", "bustes silhouettes de bustes"],
      ["🫂", "câlin bonjour"],
      ["👪", "mère père"],
      ["👣", "pied traces de pas"],
    ],
  },
  {
    id: "animals_nature",
    label: "Animaux et nature",
    icon: "🐻",
    emojis: [
      ["🐵", "singe animal"],
      ["🐒", "singe animal"],
      ["🦍", "animal gorille"],
      ["🦧", "singe animal"],
      ["🐶", "chien animal"],
      ["🐕", "chien animal"],
      ["🦮", "guide animal"],
      ["🐕‍🦺", "aide animal"],
      ["🐩", "chien animal"],
      ["🐺", "loup tête"],
      ["🦊", "tête renard"],
      ["🦝", "animal curieux"],
      ["🐱", "chat animal"],
      ["🐈", "chat animal"],
      ["🐈‍⬛", "chat noir"],
      ["🦁", "lion animal"],
      ["🐯", "tigre animal"],
      ["🐅", "tigre animal"],
      ["🐆", "animal léopard"],
      ["🐴", "animal cheval"],
      ["🐎", "cheval animal"],
      ["🦄", "tête animal"],
      ["🦓", "zèbre animal"],
      ["🦌", "cerf animal"],
      ["🦬", "bison buffle"],
      ["🐮", "vache animal"],
      ["🐂", "bœuf animal"],
      ["🐃", "buffle animal"],
      ["🐄", "vache animal"],
      ["🐷", "animal cochon"],
      ["🐖", "cochon animal"],
      ["🐗", "animal sanglier"],
      ["🐽", "groin animal"],
      ["🐏", "bélier animal"],
      ["🐑", "mouton animal"],
      ["🐐", "chèvre animal"],
      ["🐪", "animal dromadaire"],
      ["🐫", "animal chameau"],
      ["🦙", "lama laine"],
      ["🦒", "girafe animal"],
      ["🐘", "animal éléphant"],
      ["🦣", "grand laineux"],
      ["🦏", "animal rhinocéros"],
      ["🦛", "animal hippopotame"],
      ["🐭", "animal souris"],
      ["🐁", "souris animal"],
      ["🐀", "rat animal"],
      ["🐹", "tête animal"],
      ["🐰", "lapin animal"],
      ["🐇", "lapin animal"],
      ["🐿️", "animal écureuil"],
      ["🦫", "castor barrage"],
      ["🦔", "animal épineux"],
      ["🦇", "animal vampire"],
      ["🐻", "ours tête"],
      ["🐻‍❄️", "ours blanc"],
      ["🐨", "koala animal"],
      ["🐼", "tête panda"],
      ["🦥", "aï lent"],
      ["🦦", "loutre animal"],
      ["🦨", "puer odeur"],
      ["🦘", "joey saut"],
      ["🦡", "ratel animal"],
      ["🐾", "pattes empreintes"],
      ["🦃", "dindon animal"],
      ["🐔", "poule animal"],
      ["🐓", "coq animal"],
      ["🐣", "animal oiseau"],
      ["🐤", "animal oiseau"],
      ["🐥", "animal oiseau"],
      ["🐦", "oiseau animal"],
      ["🐧", "animal oiseau"],
      ["🕊️", "animal oiseau"],
      ["🦅", "aigle animal"],
      ["🦆", "canard animal"],
      ["🦢", "cygne animal"],
      ["🦉", "animal oiseau"],
      ["🦤", "dodo grand"],
      ["🪶", "plume léger"],
      ["🦩", "rose animal"],
      ["🦚", "paon fier"],
      ["🦜", "parle animal"],
      ["🐸", "tête animal"],
      ["🐊", "animal reptile"],
      ["🐢", "tortue animal"],
      ["🦎", "lézard animal"],
      ["🐍", "animal serpent"],
      ["🐲", "animal dragon"],
      ["🐉", "dragon animal"],
      ["🦕", "animal sauropode"],
      ["🦖", "T Rex t rex"],
      ["🐳", "animal baleine"],
      ["🐋", "animal baleine"],
      ["🐬", "animal dauphin"],
      ["🦭", "phoque otarie"],
      ["🐟", "animal poisson"],
      ["🐠", "animal poisson"],
      ["🐡", "animal poisson"],
      ["🦈", "requin animal"],
      ["🐙", "animal pieuvre"],
      ["🐚", "spirale coquille"],
      ["🐌", "animal escargot"],
      ["🦋", "mignon insecte"],
      ["🐛", "animal insecte"],
      ["🐜", "fourmi animal"],
      ["🐝", "animal abeille"],
      ["🪲", "insecte scarabée"],
      ["🐞", "animal insecte"],
      ["🦗", "animal criquet"],
      ["🪳", "cafard blatte"],
      ["🕷️", "animal insecte"],
      ["🕸️", "toile araignée"],
      ["🦂", "animal scorpion"],
      ["🦟", "virus fièvre"],
      ["🪰", "mouche asticot"],
      ["🪱", "ver lombric"],
      ["🦠", "amibe virus"],
      ["💐", "fleur plante"],
      ["🌸", "fleur fleur de cerisier"],
      ["💮", "fleur fleur blanche"],
      ["🏵️", "plante rosette"],
      ["🌹", "rose fleur"],
      ["🥀", "fanée fleur"],
      ["🌺", "fleur hibiscus"],
      ["🌻", "fleur tournesol"],
      ["🌼", "fleur bourgeon"],
      ["🌷", "fleur tulipe"],
      ["🌱", "plantule jeune plant"],
      ["🪴", "pousser ennuyeux"],
      ["🌲", "arbre conifère"],
      ["🌳", "arbre feuillu"],
      ["🌴", "arbre palmier"],
      ["🌵", "cactus plante"],
      ["🌾", "riz plant de riz"],
      ["🌿", "plante feuille"],
      ["☘️", "trèfle plante"],
      ["🍀", "chance trèfle"],
      ["🍁", "feuille feuille d’érable"],
      ["🍂", "feuille feuille morte"],
      ["🍃", "vent feuille"],
      ["🍄", "plante champignon"],
    ],
  },
  {
    id: "food_drink",
    label: "Nourriture et boissons",
    icon: "🍔",
    emojis: [
      ["🍇", "fruit raisin"],
      ["🍈", "melon fruit"],
      ["🍉", "fruit pastèque"],
      ["🍊", "fruit orange"],
      ["🍋", "fruit citron"],
      ["🍌", "fruit banane"],
      ["🍍", "fruit ananas"],
      ["🥭", "fruit mangue"],
      ["🍎", "fruit pomme"],
      ["🍏", "fruit pomme"],
      ["🍐", "poire fruit"],
      ["🍑", "pêche fruit"],
      ["🍒", "fruit cerises"],
      ["🍓", "fruit fraise"],
      ["🫐", "bleu baies"],
      ["🥝", "kiwi fruit"],
      ["🍅", "tomate légume"],
      ["🫒", "olive apéro"],
      ["🥥", "fruit palmier"],
      ["🥑", "fruit avocat"],
      ["🍆", "légume aubergine"],
      ["🥔", "légume patate"],
      ["🥕", "légume carotte"],
      ["🌽", "épi maïs"],
      ["🌶️", "piment piment rouge"],
      ["🫑", "légume piment"],
      ["🥒", "légume concombre"],
      ["🥬", "chou laitue"],
      ["🥦", "légume brocoli"],
      ["🧄", "ail légume"],
      ["🧅", "oignon légume"],
      ["🥜", "arachide noisette"],
      ["🌰", "plante châtaigne"],
      ["🍞", "pain miche"],
      ["🥐", "pain croissant"],
      ["🥖", "pain baguette"],
      ["🫓", "naan pita"],
      ["🥨", "bretzel torsade"],
      ["🥯", "bagel schmear"],
      ["🥞", "crêpe pancake"],
      ["🧇", "moule gaufre"],
      ["🧀", "fromage part de fromage"],
      ["🍖", "viande viande sur un os"],
      ["🍗", "poulet cuisse de poulet"],
      ["🥩", "steak côtelette"],
      ["🥓", "lard bacon"],
      ["🍔", "burger hamburger"],
      ["🍟", "frites potatœs"],
      ["🍕", "part pizza"],
      ["🌭", "hot dog saucisse"],
      ["🥪", "pain sandwich"],
      ["🌮", "taco mexicain"],
      ["🌯", "burrito mexicain"],
      ["🫔", "tamal mexicain"],
      ["🥙", "kebab falafel"],
      ["🧆", "soja seitan"],
      ["🥚", "œuf"],
      ["🍳", "œuf poêle"],
      ["🥘", "plat poêle"],
      ["🍲", "ragoût marmite"],
      ["🫕", "fondue poêlon"],
      ["🥣", "congee céréales"],
      ["🥗", "verte salade"],
      ["🍿", "pop corn"],
      ["🧈", "gras beurre"],
      ["🧂", "sel salière"],
      ["🥫", "conserve aliments en conserve"],
      ["🍱", "boîte déjeuner"],
      ["🍘", "riz cracker"],
      ["🍙", "riz plat"],
      ["🍚", "riz bol de riz"],
      ["🍛", "riz curry"],
      ["🍜", "ramen vapeur"],
      ["🍝", "pâtes spaghetti"],
      ["🍠", "patate patate douce"],
      ["🍢", "brochette brochette de poisson"],
      ["🍣", "sushi poisson"],
      ["🍤", "crevette beignet de crevette"],
      ["🍥", "poisson croquette de poisson"],
      ["🥮", "automne yuèbǐng"],
      ["🍡", "bonbons brochette de bonbons"],
      ["🥟", "gyōza jiaozi"],
      ["🥠", "prophétie biscuit chinois"],
      ["🥡", "carton chinois"],
      ["🦀", "crabe animal"],
      ["🦞", "homard bisque"],
      ["🦐", "crevette crustacé"],
      ["🦑", "calamar mollusque"],
      ["🦪", "perle huître"],
      ["🍦", "glace glace italienne"],
      ["🍧", "glace granité"],
      ["🍨", "glace crème"],
      ["🍩", "sucré dessert"],
      ["🍪", "sucré cookie"],
      ["🎂", "anniversaire gâteau d’anniversaire"],
      ["🍰", "sucré gâteau"],
      ["🧁", "cupcake sucrerie"],
      ["🥧", "tarte gâteau"],
      ["🍫", "barre sucré"],
      ["🍬", "sucré bonbon"],
      ["🍭", "sucré sucette"],
      ["🍮", "sucré dessert"],
      ["🍯", "pot miel"],
      ["🍼", "bébé lait"],
      ["🥛", "lait verre"],
      ["☕", "boisson boisson chaude"],
      ["🫖", "thé théière"],
      ["🍵", "thé tasse"],
      ["🍶", "saké bouteille"],
      ["🍾", "pop boisson"],
      ["🍷", "vin verre"],
      ["🍸", "verre cocktail"],
      ["🍹", "verre cocktail tropical"],
      ["🍺", "chope bière"],
      ["🍻", "bière trinquer"],
      ["🥂", "fêter verre"],
      ["🥃", "verre whisky"],
      ["🥤", "soda jus de fruits"],
      ["🧋", "lait bulle"],
      ["🧃", "carton jus de fruits"],
      ["🧉", "maté boisson"],
      ["🧊", "froid glace"],
      ["🥢", "hashi baguettes"],
      ["🍽️", "couteau cuisine"],
      ["🍴", "restaurant fourchette et couteau"],
      ["🥄", "couvert cuillère"],
      ["🔪", "arme outil"],
      ["🏺", "vase amphore"],
    ],
  },
  {
    id: "travel_places",
    label: "Voyages et lieux",
    icon: "✈",
    emojis: [
      ["🌍", "europe afrique"],
      ["🌎", "amérique globe tourné sur les Amériques"],
      ["🌏", "asie australie"],
      ["🌐", "globe terrestre globe avec méridiens"],
      ["🗺️", "carte carte du monde"],
      ["🗾", "carte japon"],
      ["🧭", "boussole magnétique"],
      ["🏔️", "montagne montagne enneigée"],
      ["⛰️", "montagne"],
      ["🌋", "volcan éruption"],
      ["🗻", "montagne mont Fuji"],
      ["🏕️", "camping"],
      ["🏖️", "plage parasol"],
      ["🏜️", "désert"],
      ["🏝️", "île île déserte"],
      ["🏞️", "nature parc national"],
      ["🏟️", "stade"],
      ["🏛️", "monument monument classique"],
      ["🏗️", "construction construction d’un bâtiment"],
      ["🧱", "mur brique"],
      ["🪨", "roc lourd"],
      ["🪵", "bois bûche"],
      ["🛖", "case hutte"],
      ["🏘️", "maisons bâtiments"],
      ["🏚️", "maison maison abandonnée"],
      ["🏠", "maison bâtiment"],
      ["🏡", "jardin maison"],
      ["🏢", "immeuble immeuble de bureaux"],
      ["🏣", "japon poste"],
      ["🏤", "poste bureau de poste"],
      ["🏥", "hôpital bâtiment"],
      ["🏦", "banque bâtiment"],
      ["🏨", "hôtel bâtiment"],
      ["🏩", "bâtiment love hotel"],
      ["🏪", "magasin épicerie"],
      ["🏫", "école bâtiment"],
      ["🏬", "magasin grand magasin"],
      ["🏭", "usine bâtiment"],
      ["🏯", "bâtiment château japonais"],
      ["🏰", "château bâtiment"],
      ["💒", "amour église"],
      ["🗼", "tour tokyo"],
      ["🗽", "statue statue de la Liberté"],
      ["⛪", "croix église"],
      ["🕌", "islam mosquée"],
      ["🛕", "stūpa hindou"],
      ["🕍", "juif juive"],
      ["⛩️", "shinto sanctuaire shinto"],
      ["🕋", "kaaba islam"],
      ["⛲", "fontaine"],
      ["⛺", "tente camping"],
      ["🌁", "brume brouillard"],
      ["🌃", "nuit étoiles"],
      ["🏙️", "ville bâtiment"],
      ["🌄", "soleil soleil levant derrière les montagnes"],
      ["🌅", "soleil soleil levant"],
      ["🌆", "soir immeubles"],
      ["🌇", "soleil coucher de soleil"],
      ["🌉", "pont pont de nuit"],
      ["♨️", "source sources chaudes"],
      ["🎠", "cheval manège"],
      ["🎡", "roue grande roue"],
      ["🎢", "russes montagnes"],
      ["💈", "barbier coiffure"],
      ["🎪", "cirque chapiteau"],
      ["🚂", "train locomotive"],
      ["🚃", "wagon train"],
      ["🚄", "TGV tgv"],
      ["🚅", "train train à grande vitesse"],
      ["🚆", "train chemin de fer"],
      ["🚇", "métro"],
      ["🚈", "métro métro léger"],
      ["🚉", "gare train"],
      ["🚊", "tram tramway"],
      ["🚝", "monorail véhicule"],
      ["🚞", "train train de montagne"],
      ["🚋", "tram voiture"],
      ["🚌", "bus véhicule"],
      ["🚍", "bus bus de face"],
      ["🚎", "bus trolley"],
      ["🚐", "bus minibus"],
      ["🚑", "véhicule ambulance"],
      ["🚒", "pompier camion de pompier"],
      ["🚓", "police voiture de police"],
      ["🚔", "police voiture de police de face"],
      ["🚕", "taxi véhicule"],
      ["🚖", "taxi taxi de face"],
      ["🚗", "voiture automobile"],
      ["🚘", "automobile voiture de face"],
      ["🚙", "loisirs voiture"],
      ["🛻", "pickup pick up"],
      ["🚚", "camion camion de livraison"],
      ["🚛", "semi camion"],
      ["🚜", "tracteur véhicule"],
      ["🏎️", "course voiture"],
      ["🏍️", "moto course"],
      ["🛵", "scooter"],
      ["🦽", "accessibilité fauteuil roulant manuel"],
      ["🦼", "accessibilité fauteuil roulant"],
      ["🛺", "taxi tuk tuk"],
      ["🚲", "vélo"],
      ["🛴", "trottinette"],
      ["🛹", "skate glisse"],
      ["🛼", "derby roller"],
      ["🚏", "bus arrêt de bus"],
      ["🛣️", "route autoroute"],
      ["🛤️", "train voie ferrée"],
      ["🛢️", "pétrole baril de pétrole"],
      ["⛽", "essence station"],
      ["🚨", "police lumière"],
      ["🚥", "feu tricolore"],
      ["🚦", "feu tricolore"],
      ["🛑", "stop signe"],
      ["🚧", "travaux barrière"],
      ["⚓", "ancre outil"],
      ["⛵", "mer yacht"],
      ["🛶", "canoë bateau"],
      ["🚤", "bateau hors bord"],
      ["🛳️", "bateau paquebot"],
      ["⛴️", "ferry bateau"],
      ["🛥️", "bateau bateau à moteur"],
      ["🚢", "navire bateau"],
      ["✈️", "avion véhicule"],
      ["🛩️", "avion petit avion"],
      ["🛫", "avion avion au décollage"],
      ["🛬", "avion avion à l’atterrissage"],
      ["🪂", "parachute parapente"],
      ["💺", "siège fauteuil"],
      ["🚁", "véhicule hélicoptère"],
      ["🚟", "train train suspendu"],
      ["🚠", "montagne télécabine"],
      ["🚡", "tramway télécabine"],
      ["🛰️", "espace satellite"],
      ["🚀", "fusée espace"],
      ["🛸", "ovni soucoupe volante"],
      ["🛎️", "hôtel cloche"],
      ["🧳", "bagage valise"],
      ["⌛", "sable sablier"],
      ["⏳", "sablier sablier avec sable qui coule"],
      ["⌚", "heure montre"],
      ["⏰", "heure réveil"],
      ["⏱️", "heure chronomètre"],
      ["⏲️", "heure horloge"],
      ["🕰️", "pendule horloge"],
      ["🕛", "0 h 12 h"],
      ["🕧", "00 h 30 12 h 30"],
      ["🕐", "1 h 13 h"],
      ["🕜", "1 h 30 13 h 30"],
      ["🕑", "2 h 14 h"],
      ["🕝", "2 h 30 14 h 30"],
      ["🕒", "3 h 15 h"],
      ["🕞", "3 h 30 15 h 30"],
      ["🕓", "4 h 16 h"],
      ["🕟", "4 h 30 16 h 30"],
      ["🕔", "5 h 17 h"],
      ["🕠", "5 h 30 17 h 30"],
      ["🕕", "6 h 18 h"],
      ["🕡", "6 h 30 18 h 30"],
      ["🕖", "7 h 19 h"],
      ["🕢", "7 h 30 19 h 30"],
      ["🕗", "8 h 20 h"],
      ["🕣", "8 h 30 20 h 30"],
      ["🕘", "9 h 21 h"],
      ["🕤", "9 h 30 21 h 30"],
      ["🕙", "10 h 22 h"],
      ["🕥", "10 h 30 22 h 30"],
      ["🕚", "11 h 23 h"],
      ["🕦", "11 h 30 23 h 30"],
      ["🌑", "lune nouvelle lune"],
      ["🌒", "lune lune croissante"],
      ["🌓", "lune premier quartier de lune"],
      ["🌔", "lune lune gibbeuse croissante"],
      ["🌕", "lune pleine lune"],
      ["🌖", "lune lune gibbeuse décroissante"],
      ["🌗", "lune dernier quartier"],
      ["🌘", "lune lune décroissante"],
      ["🌙", "lune croissant de lune"],
      ["🌚", "lune nouvelle lune avec visage"],
      ["🌛", "lune premier quartier de lune avec visage"],
      ["🌜", "lune dernier quartier de lune avec visage"],
      ["🌡️", "météo thermomètre"],
      ["☀️", "météo soleil"],
      ["🌝", "lune pleine lune avec visage"],
      ["🌞", "soleil soleil avec visage"],
      ["🪐", "saturne saturnien"],
      ["⭐", "étoile"],
      ["🌟", "étoile étoile brillante"],
      ["🌠", "étoile étoile filante"],
      ["🌌", "espace voie lactée"],
      ["☁️", "nuage météo"],
      ["⛅", "soleil nuageux"],
      ["⛈️", "météo orage"],
      ["🌤️", "nuage soleil derrière un petit nuage"],
      ["🌥️", "nuage soleil derrière un gros nuage"],
      ["🌦️", "nuage soleil derrière un nuage de pluie"],
      ["🌧️", "météo pluie"],
      ["🌨️", "hiver météo"],
      ["🌩️", "nuage nuage avec éclair"],
      ["🌪️", "météo nuage"],
      ["🌫️", "météo nuage"],
      ["🌬️", "vent météo"],
      ["🌀", "cyclone tourbillon"],
      ["🌈", "météo pluie"],
      ["🌂", "pluie parapluie fermé"],
      ["☂️", "pluie parapluie ouvert"],
      ["☔", "météo pluie"],
      ["⛱️", "plage soleil"],
      ["⚡", "danger éclair"],
      ["❄️", "neige flocon"],
      ["☃️", "neige bonhomme de neige"],
      ["⛄", "neige bonhomme de neige sans neige"],
      ["☄️", "comète espace"],
      ["🔥", "feu flamme"],
      ["💧", "sueur goutte d’eau"],
      ["🌊", "mer vague"],
    ],
  },
  {
    id: "activities",
    label: "Activités",
    icon: "⚽",
    emojis: [
      ["🎃", "halloween citrouille"],
      ["🎄", "fête noël"],
      ["🎆", "artifice feu d’artifice"],
      ["🎇", "fête étincelle"],
      ["🧨", "pétard dynamite"],
      ["✨", "* étoile"],
      ["🎈", "fête ballon gonflable"],
      ["🎉", "fête cotillons"],
      ["🎊", "fête confettis"],
      ["🎋", "vœux arbre"],
      ["🎍", "fête bambou"],
      ["🎎", "poupées poupées japonaises"],
      ["🎏", "fête carpe"],
      ["🎐", "fête vent"],
      ["🎑", "lune cérémonie"],
      ["🧧", "argent cadeau"],
      ["🎀", "fête ruban"],
      ["🎁", "fête cadeau"],
      ["🎗️", "ruban ruban de mémoire"],
      ["🎟️", "spectacle billet d’entrée"],
      ["🎫", "billet spectacle"],
      ["🎖️", "médaille médaille militaire"],
      ["🏆", "prix trophée"],
      ["🏅", "médaille médaille sportive"],
      ["🥇", "or 1er"],
      ["🥈", "2e argent"],
      ["🥉", "3e bronze"],
      ["⚽", "balle sport"],
      ["⚾", "balle sport"],
      ["🥎", "gant balle"],
      ["🏀", "sport basket"],
      ["🏐", "match sport"],
      ["🏈", "sport ballon"],
      ["🏉", "rugby sport"],
      ["🎾", "balle sport"],
      ["🥏", "sport frisbee"],
      ["🎳", "jeu boule"],
      ["🏏", "balle batte"],
      ["🏑", "balle sport"],
      ["🏒", "palet sport"],
      ["🥍", "but balle"],
      ["🏓", "sport partie"],
      ["🏸", "match sport"],
      ["🥊", "boxe gant"],
      ["🥋", "judo sport"],
      ["🥅", "cage filet"],
      ["⛳", "golf trou"],
      ["⛸️", "glace patin"],
      ["🎣", "pêche pêche à la ligne"],
      ["🤿", "tuba apnée"],
      ["🎽", "sport maillot de course"],
      ["🎿", "ski sport"],
      ["🛷", "luge traîneau"],
      ["🥌", "match sport"],
      ["🎯", "cible dans le mille"],
      ["🪀", "yoyo jouet"],
      ["🪁", "voler planer"],
      ["🔫", "arme pistolet"],
      ["🎱", "jeu pool"],
      ["🔮", "cristal boule de cristal"],
      ["🪄", "magie sorcier"],
      ["🎮", "manette jeu vidéo"],
      ["🕹️", "jeu joystick"],
      ["🎰", "jeu machine à sous"],
      ["🎲", "dés jeu"],
      ["🧩", "indice puzzle"],
      ["🧸", "jeu jouet"],
      ["🪅", "fête piñata"],
      ["🪆", "russe emboîté"],
      ["♠️", "jeu pique"],
      ["♥️", "jeu cœur"],
      ["♦️", "jeu carte"],
      ["♣️", "jeu trèfle"],
      ["♟️", "duper échec"],
      ["🃏", "jeu joker"],
      ["🀄", "jeu rouge"],
      ["🎴", "jeu carte"],
      ["🎭", "art masque"],
      ["🖼️", "art image"],
      ["🎨", "art peinture"],
      ["🧵", "bobine couture"],
      ["🪡", "points suture"],
      ["🧶", "fil boule"],
      ["🪢", "nœud noué"],
    ],
  },
  {
    id: "objects",
    label: "Objets",
    icon: "💡",
    emojis: [
      ["👓", "œil lunettes"],
      ["🕶️", "soleil lunettes"],
      ["🥽", "soudage lunettes"],
      ["🥼", "docteur expérience"],
      ["🦺", "fluo sûreté"],
      ["👔", "cravate vêtements"],
      ["👕", "T shirt t shirt"],
      ["👖", "jean pantalon"],
      ["🧣", "cou foulard"],
      ["🧤", "main gants"],
      ["🧥", "veste manteau"],
      ["🧦", "pieds vêtements"],
      ["👗", "robe vêtements"],
      ["👘", "kimono vêtements"],
      ["🥻", "sari mode"],
      ["🩱", "maillot de bain maillot de bain une pièce"],
      ["🩲", "slip sous vêtement"],
      ["🩳", "short caleçon"],
      ["👙", "bikini maillot de bain"],
      ["👚", "femme vêtements"],
      ["👛", "monnaie vêtements"],
      ["👜", "sac vêtements"],
      ["👝", "sac pochette"],
      ["🛍️", "sac shopping"],
      ["🎒", "sac école"],
      ["🩴", "tong tongs"],
      ["👞", "homme chaussure"],
      ["👟", "chaussure vêtements"],
      ["🥾", "marche camping"],
      ["🥿", "mule ballerine"],
      ["👠", "chaussure vêtements"],
      ["👡", "chaussure vêtements"],
      ["🩰", "danse ballet"],
      ["👢", "botte chaussure"],
      ["👑", "roi reine"],
      ["👒", "femme chapeau"],
      ["🎩", "chapeau vêtements"],
      ["🎓", "chapeau vêtements"],
      ["🧢", "vêtements casquette américaine"],
      ["🪖", "armée casque"],
      ["⛑️", "croix casque"],
      ["📿", "prière chapelet"],
      ["💄", "maquillage rouge à lèvres"],
      ["💍", "bague amour"],
      ["💎", "bijou joyau"],
      ["🔇", "son muet"],
      ["🔈", "son volume des enceintes faible"],
      ["🔉", "son volume des enceintes moyen"],
      ["🔊", "son volume des enceintes élevé"],
      ["📢", "son haut parleur"],
      ["📣", "mégaphone porte voix"],
      ["📯", "facteur cor postal"],
      ["🔔", "cloche"],
      ["🔕", "barrée cloche"],
      ["🎼", "musique partition"],
      ["🎵", "note musique"],
      ["🎶", "note notes"],
      ["🎙️", "micro micro de studio"],
      ["🎚️", "niveau curseur"],
      ["🎛️", "boutons boutons de réglage"],
      ["🎤", "micro karaoke"],
      ["🎧", "casque écouteurs"],
      ["📻", "radio vidéo"],
      ["🎷", "musique saxophone"],
      ["🪗", "accordéon bandonéon"],
      ["🎸", "guitare musique"],
      ["🎹", "piano clavier"],
      ["🎺", "musique trompette"],
      ["🎻", "violon musique"],
      ["🪕", "banjo cordes"],
      ["🥁", "musique tambour"],
      ["🪘", "conga djembé"],
      ["📱", "téléphone téléphone portable"],
      ["📲", "appel appel entrant"],
      ["☎️", "téléphone"],
      ["📞", "téléphone combiné téléphonique"],
      ["📟", "pager bipeur"],
      ["📠", "fax télécopieur"],
      ["🔋", "pile"],
      ["🔌", "prise câble avec fiche électrique"],
      ["💻", "ordinateur ordinateur portable"],
      ["🖥️", "ordinateur ordinateur de bureau"],
      ["🖨️", "imprimante ordinateur"],
      ["⌨️", "clavier ordinateur"],
      ["🖱️", "souris souris d’ordinateur"],
      ["🖲️", "ordinateur souris à boule"],
      ["💽", "disque disque d’ordinateur"],
      ["💾", "disque disquette"],
      ["💿", "CD cd"],
      ["📀", "DVD dvd"],
      ["🧮", "abaque calcul"],
      ["🎥", "film caméra"],
      ["🎞️", "film bande"],
      ["📽️", "projecteur projecteur cinématographique"],
      ["🎬", "clap film"],
      ["📺", "tv téléviseur"],
      ["📷", "vidéo appareil photo"],
      ["📸", "appareil photo appareil photo avec flash"],
      ["📹", "vidéo caméra"],
      ["📼", "vhs vidéocassette"],
      ["🔍", "loupe recherche"],
      ["🔎", "loupe recherche"],
      ["🕯️", "bougie lumière"],
      ["💡", "idée dessin"],
      ["🔦", "torche lumière"],
      ["🏮", "rouge lumière"],
      ["🪔", "diya ārtī"],
      ["📔", "carnet carnet avec couverture"],
      ["📕", "livre livre fermé"],
      ["📖", "livre livre ouvert"],
      ["📗", "livre livre vert"],
      ["📘", "livre livre bleu"],
      ["📙", "livre livre orange"],
      ["📚", "livre livres"],
      ["📓", "carnet"],
      ["📒", "grand livre carnet de compte"],
      ["📃", "page page enroulée"],
      ["📜", "papier parchemin"],
      ["📄", "page document"],
      ["📰", "journal actualités"],
      ["🗞️", "journal journal roulé"],
      ["📑", "marque signet"],
      ["🔖", "marqueur marque page"],
      ["🏷️", "étiquette"],
      ["💰", "sac argent"],
      ["🪙", "or pièce"],
      ["💴", "billet billet en yens"],
      ["💵", "billet billet en dollars"],
      ["💶", "billet billet en euros"],
      ["💷", "billet billet en livres"],
      ["💸", "billet billet avec des ailes"],
      ["💳", "carte bancaire"],
      ["🧾", "reçu preuve"],
      ["💹", "banque hausse"],
      ["✉️", "e mail enveloppe"],
      ["📧", "e mail message"],
      ["📨", "e mail message"],
      ["📩", "e mail message"],
      ["📤", "e mail message"],
      ["📥", "e mail message"],
      ["📦", "colis paquet"],
      ["📫", "courrier boîte aux lettres fermée drapeau levé"],
      ["📪", "courrier boîte aux lettres fermée drapeau baissé"],
      ["📬", "courrier boîte aux lettres ouverte drapeau levé"],
      ["📭", "courrier boîte aux lettres ouverte drapeau baissé"],
      ["📮", "courrier boîte aux lettres"],
      ["🗳️", "urne urne électorale"],
      ["✏️", "crayon"],
      ["✒️", "stylo stylo plume noir"],
      ["🖋️", "stylo stylo plume"],
      ["🖊️", "stylo stylo bille"],
      ["🖌️", "pinceau peinture"],
      ["🖍️", "pastel crayon pastel"],
      ["📝", "mémo crayon"],
      ["💼", "porte documents"],
      ["📁", "dossier fichier"],
      ["📂", "dossier dossier ouvert"],
      ["🗂️", "index classement"],
      ["📅", "date calendrier"],
      ["📆", "date éphéméride"],
      ["🗒️", "notes bloc notes à spirale"],
      ["🗓️", "calendrier calendrier à spirale"],
      ["📇", "fiche index"],
      ["📈", "hausse tendance"],
      ["📉", "baisse tendance"],
      ["📊", "graphique graphiques à barres"],
      ["📋", "porte bloc fournitures"],
      ["📌", "punaise fournitures"],
      ["📍", "épingle fournitures"],
      ["📎", "trombone fournitures"],
      ["🖇️", "trombones fournitures"],
      ["📏", "règle fournitures"],
      ["📐", "équerre fournitures"],
      ["✂️", "ciseaux fournitures"],
      ["🗃️", "dossier boîte à dossiers"],
      ["🗄️", "meuble classer"],
      ["🗑️", "corbeille corbeille à papiers"],
      ["🔒", "cadenas verrouillé"],
      ["🔓", "cadenas cadenas ouvert"],
      ["🔏", "verrouillé cadenas fermé avec stylo"],
      ["🔐", "sécurisé cadenas fermé avec clé"],
      ["🔑", "clé serrure"],
      ["🗝️", "clé serrure"],
      ["🔨", "outil marteau"],
      ["🪓", "bois hache"],
      ["⛏️", "mine outil"],
      ["⚒️", "outil pioche"],
      ["🛠️", "clé outil"],
      ["🗡️", "arme dague"],
      ["⚔️", "arme épées"],
      ["💣", "bombe dessin"],
      ["🪃", "boomerang répercussion"],
      ["🏹", "arc archer"],
      ["🛡️", "arme bouclier"],
      ["🪚", "scie bois"],
      ["🔧", "clé outil"],
      ["🪛", "vis outil"],
      ["🔩", "vis outil"],
      ["⚙️", "outil engrenage"],
      ["🗜️", "outil serre joint"],
      ["⚖️", "balance justice"],
      ["🦯", "aveugle malvoyant"],
      ["🔗", "chaînons maillons"],
      ["⛓️", "chaîne chaînes"],
      ["🪝", "ferrer crochet"],
      ["🧰", "outil coffre"],
      ["🧲", "aimant attraction"],
      ["🪜", "monter échelle"],
      ["⚗️", "outil chimie"],
      ["🧪", "labo chimie"],
      ["🧫", "labo culture"],
      ["🧬", "adn vie"],
      ["🔬", "outil science"],
      ["🔭", "outil science"],
      ["📡", "antenne parabole"],
      ["💉", "malade docteur"],
      ["🩸", "règles médecine"],
      ["💊", "pilule malade"],
      ["🩹", "bandage médecine"],
      ["🩺", "cœur docteur"],
      ["🚪", "porte"],
      ["🛗", "ascenseur accessibilité"],
      ["🪞", "glace miroir"],
      ["🪟", "vue cadre"],
      ["🛏️", "lit hôtel"],
      ["🛋️", "lampe canapé"],
      ["🪑", "assis siège"],
      ["🚽", "toilettes"],
      ["🪠", "succion ventouse"],
      ["🚿", "eau douche"],
      ["🛁", "bain baignoire"],
      ["🪤", "appât piège"],
      ["🪒", "lame raser"],
      ["🧴", "flacon lotion"],
      ["🧷", "lange couche"],
      ["🧹", "balai balayage"],
      ["🧺", "linge panier"],
      ["🧻", "essuie tout papier toilette"],
      ["🪣", "seau conteneur"],
      ["🧼", "bain savon"],
      ["🪥", "dents laver"],
      ["🧽", "éponge poreuse"],
      ["🧯", "feu incendie"],
      ["🛒", "panier chariot"],
      ["🚬", "fumeur cigarette"],
      ["⚰️", "mort cercueil"],
      ["🪦", "stèle tombe"],
      ["⚱️", "urne urne funéraire"],
      ["🧿", "nazar perle"],
      ["🗿", "moai statue"],
      ["🪧", "grève panneau"],
    ],
  },
  {
    id: "symbols",
    label: "Symboles",
    icon: "❤",
    emojis: [
      ["🏧", "dab argent"],
      ["🚮", "poubelle icône Poubelle"],
      ["🚰", "eau eau potable"],
      ["♿", "accès handicapés symbole Accès handicapés"],
      ["🚹", "wc homme"],
      ["🚺", "wc femme"],
      ["🚻", "wc toilettes"],
      ["🚼", "bébé symbole Bébé"],
      ["🚾", "WC wc"],
      ["🛂", "contrôle passeport"],
      ["🛃", "douane"],
      ["🛄", "bagages retrait des bagages"],
      ["🛅", "bagages consigne"],
      ["⚠️", "avertissement symbole d’avertissement"],
      ["🚸", "école enfants"],
      ["⛔", "interdit interdiction"],
      ["🚫", "interdit interdiction"],
      ["🚳", "vélo interdit"],
      ["🚭", "fumer interdit"],
      ["🚯", "déchets interdit"],
      ["🚱", "eau eau non potable"],
      ["🚷", "interdit interdiction"],
      ["📵", "interdit portable"],
      ["🔞", "mineur dix huit"],
      ["☢️", "symbole radioactif"],
      ["☣️", "danger symbole"],
      ["⬆️", "nord flèche"],
      ["↗️", "flèche nord est"],
      ["➡️", "est flèche"],
      ["↘️", "flèche sud est"],
      ["⬇️", "sud flèche"],
      ["↙️", "flèche direction"],
      ["⬅️", "ouest flèche"],
      ["↖️", "flèche direction"],
      ["↕️", "flèche flèche haut bas"],
      ["↔️", "flèche flèche gauche droite"],
      ["↩️", "flèche flèche courbe gauche"],
      ["↪️", "flèche flèche courbe droite"],
      ["⤴️", "flèche flèche courbe haut"],
      ["⤵️", "flèche flèche courbe bas"],
      ["🔃", "flèche sens horaire"],
      ["🔄", "flèche sens antihoraire"],
      ["🔙", "flèche flèche Retour"],
      ["🔚", "flèche flèche Fin"],
      ["🔛", "flèche flèche Activé"],
      ["🔜", "flèche flèche Bientôt"],
      ["🔝", "flèche flèche En haut"],
      ["🛐", "culte religion"],
      ["⚛️", "athée atome"],
      ["🕉️", "om hindou"],
      ["✡️", "juif david"],
      ["☸️", "roue dharma"],
      ["☯️", "tao yin"],
      ["✝️", "croix chrétien"],
      ["☦️", "croix chrétien"],
      ["☪️", "lune étoile"],
      ["☮️", "paix symbole de paix"],
      ["🕎", "menora religion"],
      ["🔯", "chance étoile"],
      ["♈", "zodiaque bélier zodiaque"],
      ["♉", "taureau zodiaque"],
      ["♊", "gémeaux zodiaque"],
      ["♋", "cancer zodiaque"],
      ["♌", "lion zodiaque"],
      ["♍", "vierge zodiaque"],
      ["♎", "balance zodiaque"],
      ["♏", "zodiaque scorpion zodiaque"],
      ["♐", "zodiaque sagittaire"],
      ["♑", "zodiaque capricorne"],
      ["♒", "verseau zodiaque"],
      ["♓", "poissons zodiaque"],
      ["⛎", "zodiaque ophiuchus"],
      ["🔀", "flèche flèches croisées"],
      ["🔁", "flèche sens horaire"],
      ["🔂", "flèche sens horaire"],
      ["▶️", "flèche lecture"],
      ["⏩", "avance avance rapide"],
      ["⏭️", "suivant triangle"],
      ["⏯️", "pause flèche"],
      ["◀️", "flèche gauche"],
      ["⏪", "flèche retour"],
      ["⏮️", "triangle précédent"],
      ["🔼", "flèche petit triangle haut"],
      ["⏫", "flèche vers le haut double flèche vers le haut"],
      ["🔽", "flèche petit triangle bas"],
      ["⏬", "bas flèche vers le bas"],
      ["⏸️", "pause bouton pause"],
      ["⏹️", "stop carré"],
      ["⏺️", "cercle enregistrer"],
      ["⏏️", "éjecter bouton éjecter"],
      ["🎦", "film cinéma"],
      ["🔅", "luminosité luminosité faible"],
      ["🔆", "luminosité luminosité élevée"],
      ["📶", "réseau portable"],
      ["📳", "vibreur portable"],
      ["📴", "portable téléphone"],
      ["♀️", "femme symbole de la femme"],
      ["♂️", "homme symbole de l’homme"],
      ["⚧️", "transgenre symbole de la communauté transgenre"],
      ["✖️", "* x"],
      ["➕", "+ plus"],
      ["➖", "  −"],
      ["➗", "÷ signe"],
      ["♾️", "infini illimité"],
      ["‼️", "! !!"],
      ["⁉️", "! ?"],
      ["❓", "? question"],
      ["❔", "? question"],
      ["❕", "! exclamation"],
      ["❗", "! exclamation"],
      ["〰️", "vague ponctuation"],
      ["💱", "argent banque"],
      ["💲", "argent dollar"],
      ["⚕️", "caducée médecine"],
      ["♻️", "recyclage symbole Recyclage"],
      ["⚜️", "fleur de lys"],
      ["🔱", "ancre bateau"],
      ["📛", "nom badge"],
      ["🔰", "débutant symbole japonais de débutant"],
      ["⭕", "0 o"],
      ["✅", "✓ oui"],
      ["☑️", "✓ oui"],
      ["✔️", "✓ oui"],
      ["❌", "x ×"],
      ["❎", "x ×"],
      ["➰", "boucle bouclette"],
      ["➿", "boucle double boucle"],
      ["〽️", "symbole alternance"],
      ["✳️", "* huit"],
      ["✴️", "* huit"],
      ["❇️", "* éclat"],
      ["©️", "c ©"],
      ["®️", "r ®"],
      ["™️", "marque déposée marque commerciale déposée"],
      ["#️⃣", "touches touches : #"],
      ["*️⃣", "touches touches : *"],
      ["0️⃣", "touches touches : 0"],
      ["1️⃣", "touches touches : 1"],
      ["2️⃣", "touches touches : 2"],
      ["3️⃣", "touches touches : 3"],
      ["4️⃣", "touches touches : 4"],
      ["5️⃣", "touches touches : 5"],
      ["6️⃣", "touches touches : 6"],
      ["7️⃣", "touches touches : 7"],
      ["8️⃣", "touches touches : 8"],
      ["9️⃣", "touches touches : 9"],
      ["🔟", "touches touches : 10"],
      ["🔠", "saisie lettres"],
      ["🔡", "saisie lettres"],
      ["🔢", "1234 saisie"],
      ["🔣", "saisie symboles"],
      ["🔤", "saisie lettres"],
      ["🅰️", "a groupe sanguin"],
      ["🆎", "ab groupe sanguin"],
      ["🅱️", "b groupe sanguin"],
      ["🆑", "effacer bouton Effacer"],
      ["🆒", "cool bouton Cool"],
      ["🆓", "gratuit bouton Gratuit"],
      ["ℹ️", "i informations"],
      ["🆔", "identifiant bouton Identifiant"],
      ["Ⓜ️", "m cercle"],
      ["🆕", "nouveau bouton Nouveau"],
      ["🆖", "mauvais interdit"],
      ["🅾️", "o groupe sanguin"],
      ["🆗", "ok bouton OK"],
      ["🅿️", "parking bouton P"],
      ["🆘", "sos bouton SOS"],
      ["🆙", "nouveau nouveauté"],
      ["🆚", "vs contre"],
      ["🈁", "ici japonais"],
      ["🈂️", "japonais frais de service"],
      ["🈷️", "japonais montant mensuel"],
      ["🈶", "payant japonais"],
      ["🈯", "réservé japonais"],
      ["🉐", "japonais bonne affaire"],
      ["🈹", "rabais japonais"],
      ["🈚", "gratuit japonais"],
      ["🈲", "japonais bouton interdit en japonais"],
      ["🉑", "accepter japonais"],
      ["🈸", "japonais application"],
      ["🈴", "japonais note pour réussir"],
      ["🈳", "japonais chambres disponibles"],
      ["㊗️", "japonais félicitations"],
      ["㊙️", "secret japonais"],
      ["🈺", "japonais ouvert pour affaires"],
      ["🈵", "complet japonais"],
      ["🔴", "rond rouge"],
      ["🟠", "rond cercle"],
      ["🟡", "rond jaune"],
      ["🟢", "rond vert"],
      ["🔵", "bleu rond"],
      ["🟣", "rond cercle"],
      ["🟤", "rond cercle"],
      ["⚫", "noir rond"],
      ["⚪", "rond blanc"],
      ["🟥", "rouge géométrie"],
      ["🟧", "orange géométrie"],
      ["🟨", "jaune géométrie"],
      ["🟩", "vert géométrie"],
      ["🟦", "bleu géométrie"],
      ["🟪", "violet géométrie"],
      ["🟫", "marron géométrie"],
      ["⬛", "carré grand carré noir"],
      ["⬜", "forme géométrie"],
      ["◼️", "carré carré moyen noir"],
      ["◻️", "carré carré moyen blanc"],
      ["◾", "carré forme"],
      ["◽", "carré forme"],
      ["▪️", "carré petit carré noir"],
      ["▫️", "carré petit carré blanc"],
      ["🔶", "losange forme géométrique"],
      ["🔷", "losange forme géométrique"],
      ["🔸", "losange forme géométrique"],
      ["🔹", "losange forme géométrique"],
      ["🔺", "rouge forme géométrique"],
      ["🔻", "forme flèche"],
      ["💠", "dessin diamant"],
      ["🔘", "forme radio"],
      ["🔳", "carré forme"],
      ["🔲", "carré forme"],
    ],
  },
  {
    id: "flags",
    label: "Drapeaux",
    icon: "🏁",
    emojis: [
      ["🏁", "drapeau drapeau à damier"],
      ["🚩", "fanion drapeau"],
      ["🎌", "drapeaux drapeaux croisés"],
      ["🏴", "drapeau drapeau noir"],
      ["🏳️", "drapeau drapeau blanc"],
      ["🏳️‍🌈", "drapeau arc en ciel"],
      ["🏳️‍⚧️", "rose blanc"],
      ["🏴‍☠️", "piller pirate"],
      ["🇦🇨", "AC drapeau"],
      ["🇦🇩", "AD drapeau"],
      ["🇦🇪", "AE drapeau"],
      ["🇦🇫", "AF drapeau"],
      ["🇦🇬", "AG drapeau"],
      ["🇦🇮", "AI drapeau"],
      ["🇦🇱", "AL drapeau"],
      ["🇦🇲", "AM drapeau"],
      ["🇦🇴", "AO drapeau"],
      ["🇦🇶", "AQ drapeau"],
      ["🇦🇷", "AR drapeau"],
      ["🇦🇸", "AS drapeau"],
      ["🇦🇹", "AT drapeau"],
      ["🇦🇺", "AU drapeau"],
      ["🇦🇼", "AW drapeau"],
      ["🇦🇽", "AX drapeau"],
      ["🇦🇿", "AZ drapeau"],
      ["🇧🇦", "BA drapeau"],
      ["🇧🇧", "BB drapeau"],
      ["🇧🇩", "BD drapeau"],
      ["🇧🇪", "BE drapeau"],
      ["🇧🇫", "BF drapeau"],
      ["🇧🇬", "BG drapeau"],
      ["🇧🇭", "BH drapeau"],
      ["🇧🇮", "BI drapeau"],
      ["🇧🇯", "BJ drapeau"],
      ["🇧🇱", "BL drapeau"],
      ["🇧🇲", "BM drapeau"],
      ["🇧🇳", "BN drapeau"],
      ["🇧🇴", "BO drapeau"],
      ["🇧🇶", "BQ drapeau"],
      ["🇧🇷", "BR drapeau"],
      ["🇧🇸", "BS drapeau"],
      ["🇧🇹", "BT drapeau"],
      ["🇧🇻", "BV drapeau"],
      ["🇧🇼", "BW drapeau"],
      ["🇧🇾", "BY drapeau"],
      ["🇧🇿", "BZ drapeau"],
      ["🇨🇦", "CA drapeau"],
      ["🇨🇨", "CC drapeau"],
      ["🇨🇩", "CD drapeau"],
      ["🇨🇫", "CF drapeau"],
      ["🇨🇬", "CG drapeau"],
      ["🇨🇭", "CH drapeau"],
      ["🇨🇮", "CI drapeau"],
      ["🇨🇰", "CK drapeau"],
      ["🇨🇱", "CL drapeau"],
      ["🇨🇲", "CM drapeau"],
      ["🇨🇳", "CN drapeau"],
      ["🇨🇴", "CO drapeau"],
      ["🇨🇵", "CP drapeau"],
      ["🇨🇷", "CR drapeau"],
      ["🇨🇺", "CU drapeau"],
      ["🇨🇻", "CV drapeau"],
      ["🇨🇼", "CW drapeau"],
      ["🇨🇽", "CX drapeau"],
      ["🇨🇾", "CY drapeau"],
      ["🇨🇿", "CZ drapeau"],
      ["🇩🇪", "DE drapeau"],
      ["🇩🇬", "DG drapeau"],
      ["🇩🇯", "DJ drapeau"],
      ["🇩🇰", "DK drapeau"],
      ["🇩🇲", "DM drapeau"],
      ["🇩🇴", "DO drapeau"],
      ["🇩🇿", "DZ drapeau"],
      ["🇪🇦", "EA drapeau"],
      ["🇪🇨", "EC drapeau"],
      ["🇪🇪", "EE drapeau"],
      ["🇪🇬", "EG drapeau"],
      ["🇪🇭", "EH drapeau"],
      ["🇪🇷", "ER drapeau"],
      ["🇪🇸", "ES drapeau"],
      ["🇪🇹", "ET drapeau"],
      ["🇪🇺", "EU drapeau"],
      ["🇫🇮", "FI drapeau"],
      ["🇫🇯", "FJ drapeau"],
      ["🇫🇰", "FK drapeau"],
      ["🇫🇲", "FM drapeau"],
      ["🇫🇴", "FO drapeau"],
      ["🇫🇷", "FR drapeau"],
      ["🇬🇦", "GA drapeau"],
      ["🇬🇧", "GB drapeau"],
      ["🇬🇩", "GD drapeau"],
      ["🇬🇪", "GE drapeau"],
      ["🇬🇫", "GF drapeau"],
      ["🇬🇬", "GG drapeau"],
      ["🇬🇭", "GH drapeau"],
      ["🇬🇮", "GI drapeau"],
      ["🇬🇱", "GL drapeau"],
      ["🇬🇲", "GM drapeau"],
      ["🇬🇳", "GN drapeau"],
      ["🇬🇵", "GP drapeau"],
      ["🇬🇶", "GQ drapeau"],
      ["🇬🇷", "GR drapeau"],
      ["🇬🇸", "GS drapeau"],
      ["🇬🇹", "GT drapeau"],
      ["🇬🇺", "GU drapeau"],
      ["🇬🇼", "GW drapeau"],
      ["🇬🇾", "GY drapeau"],
      ["🇭🇰", "HK drapeau"],
      ["🇭🇲", "HM drapeau"],
      ["🇭🇳", "HN drapeau"],
      ["🇭🇷", "HR drapeau"],
      ["🇭🇹", "HT drapeau"],
      ["🇭🇺", "HU drapeau"],
      ["🇮🇨", "IC drapeau"],
      ["🇮🇩", "ID drapeau"],
      ["🇮🇪", "IE drapeau"],
      ["🇮🇱", "IL drapeau"],
      ["🇮🇲", "IM drapeau"],
      ["🇮🇳", "IN drapeau"],
      ["🇮🇴", "IO drapeau"],
      ["🇮🇶", "IQ drapeau"],
      ["🇮🇷", "IR drapeau"],
      ["🇮🇸", "IS drapeau"],
      ["🇮🇹", "IT drapeau"],
      ["🇯🇪", "JE drapeau"],
      ["🇯🇲", "JM drapeau"],
      ["🇯🇴", "JO drapeau"],
      ["🇯🇵", "JP drapeau"],
      ["🇰🇪", "KE drapeau"],
      ["🇰🇬", "KG drapeau"],
      ["🇰🇭", "KH drapeau"],
      ["🇰🇮", "KI drapeau"],
      ["🇰🇲", "KM drapeau"],
      ["🇰🇳", "KN drapeau"],
      ["🇰🇵", "KP drapeau"],
      ["🇰🇷", "KR drapeau"],
      ["🇰🇼", "KW drapeau"],
      ["🇰🇾", "KY drapeau"],
      ["🇰🇿", "KZ drapeau"],
      ["🇱🇦", "LA drapeau"],
      ["🇱🇧", "LB drapeau"],
      ["🇱🇨", "LC drapeau"],
      ["🇱🇮", "LI drapeau"],
      ["🇱🇰", "LK drapeau"],
      ["🇱🇷", "LR drapeau"],
      ["🇱🇸", "LS drapeau"],
      ["🇱🇹", "LT drapeau"],
      ["🇱🇺", "LU drapeau"],
      ["🇱🇻", "LV drapeau"],
      ["🇱🇾", "LY drapeau"],
      ["🇲🇦", "MA drapeau"],
      ["🇲🇨", "MC drapeau"],
      ["🇲🇩", "MD drapeau"],
      ["🇲🇪", "ME drapeau"],
      ["🇲🇫", "MF drapeau"],
      ["🇲🇬", "MG drapeau"],
      ["🇲🇭", "MH drapeau"],
      ["🇲🇰", "MK drapeau"],
      ["🇲🇱", "ML drapeau"],
      ["🇲🇲", "MM drapeau"],
      ["🇲🇳", "MN drapeau"],
      ["🇲🇴", "MO drapeau"],
      ["🇲🇵", "MP drapeau"],
      ["🇲🇶", "MQ drapeau"],
      ["🇲🇷", "MR drapeau"],
      ["🇲🇸", "MS drapeau"],
      ["🇲🇹", "MT drapeau"],
      ["🇲🇺", "MU drapeau"],
      ["🇲🇻", "MV drapeau"],
      ["🇲🇼", "MW drapeau"],
      ["🇲🇽", "MX drapeau"],
      ["🇲🇾", "MY drapeau"],
      ["🇲🇿", "MZ drapeau"],
      ["🇳🇦", "NA drapeau"],
      ["🇳🇨", "NC drapeau"],
      ["🇳🇪", "NE drapeau"],
      ["🇳🇫", "NF drapeau"],
      ["🇳🇬", "NG drapeau"],
      ["🇳🇮", "NI drapeau"],
      ["🇳🇱", "NL drapeau"],
      ["🇳🇴", "NO drapeau"],
      ["🇳🇵", "NP drapeau"],
      ["🇳🇷", "NR drapeau"],
      ["🇳🇺", "NU drapeau"],
      ["🇳🇿", "NZ drapeau"],
      ["🇴🇲", "OM drapeau"],
      ["🇵🇦", "PA drapeau"],
      ["🇵🇪", "PE drapeau"],
      ["🇵🇫", "PF drapeau"],
      ["🇵🇬", "PG drapeau"],
      ["🇵🇭", "PH drapeau"],
      ["🇵🇰", "PK drapeau"],
      ["🇵🇱", "PL drapeau"],
      ["🇵🇲", "PM drapeau"],
      ["🇵🇳", "PN drapeau"],
      ["🇵🇷", "PR drapeau"],
      ["🇵🇸", "PS drapeau"],
      ["🇵🇹", "PT drapeau"],
      ["🇵🇼", "PW drapeau"],
      ["🇵🇾", "PY drapeau"],
      ["🇶🇦", "QA drapeau"],
      ["🇷🇪", "RE drapeau"],
      ["🇷🇴", "RO drapeau"],
      ["🇷🇸", "RS drapeau"],
      ["🇷🇺", "RU drapeau"],
      ["🇷🇼", "RW drapeau"],
      ["🇸🇦", "SA drapeau"],
      ["🇸🇧", "SB drapeau"],
      ["🇸🇨", "SC drapeau"],
      ["🇸🇩", "SD drapeau"],
      ["🇸🇪", "SE drapeau"],
      ["🇸🇬", "SG drapeau"],
      ["🇸🇭", "SH drapeau"],
      ["🇸🇮", "SI drapeau"],
      ["🇸🇯", "SJ drapeau"],
      ["🇸🇰", "SK drapeau"],
      ["🇸🇱", "SL drapeau"],
      ["🇸🇲", "SM drapeau"],
      ["🇸🇳", "SN drapeau"],
      ["🇸🇴", "SO drapeau"],
      ["🇸🇷", "SR drapeau"],
      ["🇸🇸", "SS drapeau"],
      ["🇸🇹", "ST drapeau"],
      ["🇸🇻", "SV drapeau"],
      ["🇸🇽", "SX drapeau"],
      ["🇸🇾", "SY drapeau"],
      ["🇸🇿", "SZ drapeau"],
      ["🇹🇦", "TA drapeau"],
      ["🇹🇨", "TC drapeau"],
      ["🇹🇩", "TD drapeau"],
      ["🇹🇫", "TF drapeau"],
      ["🇹🇬", "TG drapeau"],
      ["🇹🇭", "TH drapeau"],
      ["🇹🇯", "TJ drapeau"],
      ["🇹🇰", "TK drapeau"],
      ["🇹🇱", "TL drapeau"],
      ["🇹🇲", "TM drapeau"],
      ["🇹🇳", "TN drapeau"],
      ["🇹🇴", "TO drapeau"],
      ["🇹🇷", "TR drapeau"],
      ["🇹🇹", "TT drapeau"],
      ["🇹🇻", "TV drapeau"],
      ["🇹🇼", "TW drapeau"],
      ["🇹🇿", "TZ drapeau"],
      ["🇺🇦", "UA drapeau"],
      ["🇺🇬", "UG drapeau"],
      ["🇺🇲", "UM drapeau"],
      ["🇺🇳", "UN drapeau"],
      ["🇺🇸", "US drapeau"],
      ["🇺🇾", "UY drapeau"],
      ["🇺🇿", "UZ drapeau"],
      ["🇻🇦", "VA drapeau"],
      ["🇻🇨", "VC drapeau"],
      ["🇻🇪", "VE drapeau"],
      ["🇻🇬", "VG drapeau"],
      ["🇻🇮", "VI drapeau"],
      ["🇻🇳", "VN drapeau"],
      ["🇻🇺", "VU drapeau"],
      ["🇼🇫", "WF drapeau"],
      ["🇼🇸", "WS drapeau"],
      ["🇽🇰", "XK drapeau"],
      ["🇾🇪", "YE drapeau"],
      ["🇾🇹", "YT drapeau"],
      ["🇿🇦", "ZA drapeau"],
      ["🇿🇲", "ZM drapeau"],
      ["🇿🇼", "ZW drapeau"],
      ["🏴󠁧󠁢󠁥󠁮󠁧󠁿", "gbeng drapeau"],
      ["🏴󠁧󠁢󠁳󠁣󠁴󠁿", "gbsct drapeau"],
      ["🏴󠁧󠁢󠁷󠁬󠁳󠁿", "gbwls drapeau"],
    ],
  },
];
